### ISSUE TITLE
建议提供一个自建库模式

### ISSUE THREAD

**Issue by mJqalJqN** [Kaiyiwing/qwerty-learner#102]
可能我没找到，如果没有目的性练习，容易造成负担。谢谢。有微信打赏吗

**Comment by chengluyu** [comment]
请问您说的「自建库」是否和 #75 类似？

**Comment by mJqalJqN** [comment]
yes

**Comment by chengluyu** [comment]
Close due to duplication. You can turn to #75. Thanks for suggestion! 😊
