### ISSUE TITLE
建议添加一个复读功能

### ISSUE THREAD

**Issue by chinayangzhan913** [Kaiyiwing/qwerty-learner#103]
建议添加一个复读功能。 比如按空格可以再听一次单词读音。有时候单词读音一遍没听清，只能打错重新听一遍，而打错又会影响准确率 :(

**Comment by yzh979** [comment]
我也附议增加单词复读功能。或者这么设计：单词输入到末尾。输入回车键就是重复当前这个单词，输入空格键和现在一样进入下一个单词。

**Comment by Kaiyiwing** [comment]
我倾向于使用空格键重复播放单词读音的设计，但我近期在忙论文的 ddl，功能实现上会晚一些。
如果有人对实现此功能感兴趣，非常欢迎提交 pr，我会及时的 review code。
