### ISSUE TITLE
There is a wrong word in SAT chapter12

### ISSUE THREAD

**Issue by cicihou** [Kaiyiwing/qwerty-learner#104]
![image](https://user-images.githubusercontent.com/41445818/111276820-b79f5b80-8672-11eb-91a1-76b804a8e8e0.png)

I hope there could be a specific issue to help us correct the similar misspellings. :)

**Comment by Kaiyiwing** [comment]
已经修改
因为目前使用的是第三方开源的字典库，不可避免的会有些许错误。
