### ISSUE TITLE
如何部署呢？

### ISSUE THREAD

**Issue by landlordlycat** [Kaiyiwing/qwerty-learner#106]
我访问gitee页面好慢。一直转圈圈。不知道能否搭建在本地或者网站上。

**Comment by Kaiyiwing** [comment]
首先 clone 项目，在根目录下执行 `yarn` 命令安装软件所需的包  
安装完成后，执行 `yarn start` 进入开发模式  
如果想打包部署，可以运行 `yarn build` 打包到`build`目录，可以部署到任意服务器上

**Comment by landlordlycat** [comment]
好，谢谢了~

**Comment by Kaiyiwing** [comment]
在 `package.json` 中，找到`"build": "CI=false craco build",`修改为`"build": "craco build"`

**Comment by landlordlycat** [comment]
> 在 `package.json` 中，找到`"build": "CI=false craco build",`修改为`"build": "craco build"`
> 
> 我这边运行是没问题的，可能是 win 和 mac 设置环境变量的方式不一样

对。成功了。谢谢了

**Comment by Kaiyiwing** [comment]
@landlordlycat 🎉🎉🎉

**Comment by chengluyu** [comment]
Fixed in #107.
