### ISSUE TITLE
Some advice about new features after use for several days

### ISSUE THREAD

**Issue by DanielBamboo** [Kaiyiwing/qwerty-learner#109]
This is a great project that benefits someone sit in front of the computer all day, and I **truely** like it. I have some advice about this project (web)

1. When I type a wrong word, I hope there is a **red warning** to show it.
2. Maybe a **history record** would make long-term learning better, because I want to use it as a daily tool
3. A new mode to make these placeholders invisible
4. A "Back to the Previous Word" Button
5. A link to its detail meaning

**Comment by Kaiyiwing** [comment]
Thanks for your kind suggestions!

1. It's like we already have the red warning. when use input wrong letter, the wrong letter gonna be red and the whole word will shaking.
2. We are thinking about this, but right now, most main contributors are working at paper ddl. PRs are welcomed.
3. I'm not sure about your suggestion. You mean make the placeholders invisible when user open 'recite mode' ? 
4. That's a cool idea! Right now there are many cool ideas about the UX, but personally I enjoy the current concise UI. So I will discuss with main contributors.
5. We were discuss about add example sentence or something like that. For me, I think the main aim of this project is training the typing speed, too much information maybe not necessary.

I'm open to suggestions

**Comment by DanielBamboo** [comment]
Thanks for your sincere reply !

1. about the red warning: 
I forgot to say this is in "recite mode", When I type a wrong key, I want that key appear and shake, but in fact the whole word just gone and force me to type again, I don't know what's the wrong key I have pressed. 

3. Yes, I mean the "recite mode", for me, this project is not only a tool to train English typing speed,but a good way to learn English, so, these placeholders in "recite mode" would make me guess whats the next word but not try to remember what it really is. 

# My feeling
I'm a student now preparing for _the national entrance examination for postgraduates_, Currently I have some problems on learning English, but a game-like typing exercise is very attractive, so I come to this website to train my English these days, this project is great! Actually I am seeking for something like this for a long time.

I am also a CS student, every day I have to work or study in front of a screen, so the keyboard is the fastest way for me to enjoy learning something. for some English-learning mobile application it has similar idea but I think typing in cellphone is not an easy thing. That's why I think this project is great to people like me. 

I know the aim to this project is to train English typing speed, after reading the opening issues I found they also hope this project be more like a English-learning app, of course, all my advice is based on my English-learning purpose. 

I wanna say I am quite happy working with this app, so just go forward to your original goal to make it better.

My English is not good so that I can't make my opinion clear, sorry for that.

 I know you were also Chinese, but I saw there are also English speakers in contributors, so I decided to write this issue in English. 

:-)
