### ISSUE TITLE
It doesn't work on github.io website?

### ISSUE THREAD

**Issue by paint1024** [Kaiyiwing/qwerty-learner#110]
Hi,

 I just forked this cool project, but it didn't show up on my github.io website.
Will you help me with how to solve this problem?

**Comment by Kaiyiwing** [comment]
I use travis to deploy the project to 'gh-pages' branch automatically, and set github.io to 'gh-pages'.
So you need travis to do same thing.

But personally speaking, I recommend you try [vercel](https://vercel.com/), it's better than github.io.

**Comment by chengluyu** [comment]
Hi, this repository only contains source code, so forking this project won’t deploy it. You can manually build and deploy the project according to @Kaiyiwing’s response.
