### ISSUE TITLE
与Firefox浏览器的兼容问题

### ISSUE THREAD

**Issue by CXZS-Git** [Kaiyiwing/qwerty-learner#111]
在浏览网页时直接输入，会被Firefox识别成页面内查找，相当于按下Ctrl+F。
所以在贵网站中进行输入时，只能输入第一个字母，剩下的字母均会被Firefox输入到页面内查找框中。

**Comment by Kaiyiwing** [comment]
我在 FireFox 中未发现该问题，或许与你浏览器设置或者插件有关？
环境：Mac、 FireFox Developer Edition

**Comment by CXZS-Git** [comment]
![图片](https://user-images.githubusercontent.com/3448255/113365348-8b7d1d80-9388-11eb-8a21-f2be18f4fa28.png)
的确是浏览器设置问题，取消勾选这个选项就可以正常使用贵网站了。
