### ISSUE TITLE
增加词根词缀的显示, 来辅助记忆

### ISSUE THREAD

**Issue by stevieyu** [Kaiyiwing/qwerty-learner#112]
可否增加词根和词缀的显示, 辅助加深记忆, 遇到比较长的单词, 词根有利于记忆

**Comment by chengluyu** [comment]
Thanks for your suggestions! Could you please give some examples?

**Comment by stevieyu** [comment]
acceleration
ac -  前缀，意思为“加强
celer - 词根 表示"快,速度"
ion - 后缀 动作或状态

ex（向外）+press→内心的想法向外压→表达
im（向里）+press→外在的东西向内心压→使...有印象
de（向下/加强）+press→向下用力压→使...压抑，损坏
com（共同）+press→几个方向共同压→压缩
re（反复）+press→（暴乱或起义）屡禁不止→镇压
