### ISSUE TITLE
建议增加字典章节对应列表总览

### ISSUE THREAD

**Issue by doraemon00** [Kaiyiwing/qwerty-learner#123]
方便自己背诵或者敲完之后，更好的复习。 建议增加列表的目的是为了方便重复复习。

**Comment by Kaiyiwing** [comment]
🤔 你的意思是在列表中增加已背诵的标志么？

**Comment by doraemon00** [comment]
![Snipaste_2021-07-28_10-39-17](https://user-images.githubusercontent.com/37154545/127255063-d2b5b712-10b9-496e-a88b-aac2f1c33a90.png)
是的。类似一个单独的列表，对应每个章节中的单词。因为体验上来看不知道今天背了什么，只是单纯的打字练习，无法查看，感觉就少了复习的流程。以上只是自己使用过程中的一些想法，有不对的地方请忽略。感谢这样好的软件

**Comment by chengluyu** [comment]
这个主意还不错，有空试一下。
