### ISSUE TITLE
建议加入日常英语多少句之类的来练习

### ISSUE THREAD

**Issue by s5s5** [Kaiyiwing/qwerty-learner#126]
单词练够了，还可以练练句子，小短文什么的，哈

**Comment by Kaiyiwing** [comment]
🌝之前有过这个想法，会单独做一个产品来练习句子。 目前的话，市面上也有一些产品可以练习句子，可以参考这篇文章：https://sspai.com/post/67535

**Comment by s5s5** [comment]
我觉得可以和上面这些做出差异性：

- 因为咱们这个切入点可以是 面向母语非英文用户的学习英语体验 ，而少数派上的都是在练习打字
- 背单词就是第一步（说到这里是不是应该加入艾宾浩斯遗忘曲线？）
- 那么常用英语句型就是要背诵的第二步了
- 第三步可以加入考试，也许还给发个证啥的，哈哈哈

**Comment by chengluyu** [comment]
本项目的目的还是练习单词的「肌肉记忆」，所以目前只有重复练习单词的功能。如果加入练习句子和文章的话，可能会以别的方式呈现。
