### ISSUE TITLE
急需随机等排序方式显示！

### ISSUE THREAD

**Issue by Mutoumiao** [Kaiyiwing/qwerty-learner#129]
由于记忆很大程度会因为排序重复原因导致不是真正记忆到单词，而只是因为顺序过多的熟悉，因此希望能够添加多种排序方式，比如随机，倒序等等。非常感谢！

**Comment by chengluyu** [comment]
同意。

**Comment by chengluyu** [comment]
@Kaiyiwing 我在做这个功能，提交 PR 后可以和 #128 一起关闭。

**Comment by Oct1a** [comment]
> @Kaiyiwing 我在做这个功能，提交 PR 后可以和 #128 一起关闭。

催更催更😂

**Comment by Oct1a** [comment]
> @Kaiyiwing 我在做这个功能，提交 PR 后可以和 #128 一起关闭。

话说怎么提交词库?已经弄成json格式了，能直接PR吗

**Comment by Kaiyiwing** [comment]
> > @Kaiyiwing 我在做这个功能，提交 PR 后可以和 #128 一起关闭。
> 
> 话说怎么提交词库?已经弄成json格式了，能直接PR吗

参考 Issue #40  pr #67  贡献词典
