### ISSUE TITLE
在关闭英文显示进行默写阶段时，我希望可以具备一个关闭预知道多少字母功能。

### ISSUE THREAD

**Issue by Mutoumiao** [Kaiyiwing/qwerty-learner#131]
如标题，在进行深度复习时，当我们进行默写时，希望有个选项可以关闭显示 _ _ _ _ _ _ 的具体单词数量，可以通过样式把该内容进行隐藏，当输入时恢复正常绿色英文。

因为深度复习默写时并不推荐有任何提示，你去检索真正记忆的中的单词辅助。当然此功能应当有开关，方便适应不同人群。

PS：额外提一下，如果可以，希望在ipad下，可以提供一个输入框，让我具备通过手写的方式输入，键盘记忆有时候并不等于手写记忆，

上面所提的也是为了更大程度避免键盘的记忆，而更大化通过复习利用真正的自我的长期记忆来保存。非常感谢

**Comment by Mutoumiao** [comment]
比起隐藏 _ _ _ _的做法，更希望日后具备完全默写功能，例如：
1.不提供显示具体单词数量
2.只有在完全输入完后，回车确认才可校验是否通过（极大化自我回想），避免出现尝试多次试错机会（目前模式）。

以上模式只是额外的默写模式，可以通过默写模式的选择来进行挑选。非常感谢关注请求

**Comment by Kaiyiwing** [comment]
> > PS：额外提一下，如果可以，希望在ipad下，可以提供一个输入框，让我具备通过手写的方式输入，键盘记忆有时候并不等于手写记忆，
> 
> 单独回复这句。前端做手写识别可以，但会让项目更臃肿（不论是从功能上还是从大小上）。用原生应用做这种功能更方便，我突然想把之前那个 SwiftUI 仿的 QWERTY Learner 拾起来了，@Kaiyiwing 有什么看法吗？

ipad + apple pencil 用来做手写背单词的软件感觉还可以，如果是用手指的话，感觉体验并不好 🤔

**Comment by Mutoumiao** [comment]
> > > PS：额外提一下，如果可以，希望在ipad下，可以提供一个输入框，让我具备通过手写的方式输入，键盘记忆有时候并不等于手写记忆，
> > 
> > 
> > 单独回复这句。 前端做手写识别可以，但会让项目更臃肿（不论是从功能上还是从大小上）。 用原生应用做这种功能更方便，我突然想把之前那个 SwiftUI 仿的 QWERTY Learner 拾起来了，@Kaiyiwing 有什么看法吗？
> 
> ipad + apple pencil 用来做手写背单词的软件感觉还可以，如果是用手指的话，感觉体验并不好 🤔

本ipad + apple pencil就已经具备输入区域手写识别功能，因此一开始的想法只是需要一个输入的区域即可，就类似识别ipad访问时，多出个按钮点击引导，可以点击按钮后，再通过输入框进行手写输入也行。（可能是个比较粗糙的想法，大佬仅供参考）

**Comment by chengluyu** [comment]
> > > > PS：额外提一下，如果可以，希望在ipad下，可以提供一个输入框，让我具备通过手写的方式输入，键盘记忆有时候并不等于手写记忆，
> > > 
> > > 
> > > 单独回复这句。 前端做手写识别可以，但会让项目更臃肿（不论是从功能上还是从大小上）。 用原生应用做这种功能更方便，我突然想把之前那个 SwiftUI 仿的 QWERTY Learner 拾起来了，@Kaiyiwing 有什么看法吗？
> > 
> > 
> > ipad + apple pencil 用来做手写背单词的软件感觉还可以，如果是用手指的话，感觉体验并不好 🤔
> 
> 本ipad + apple pencil就已经具备输入区域手写识别功能，因此一开始的想法只是需要一个输入的区域即可，就类似识别ipad访问时，多出个按钮点击引导，可以点击按钮后，再通过输入框进行手写输入也行。（可能是个比较粗糙的想法，大佬仅供参考）

对哦，我都忘记这个功能了。其实只要提供一个 `UITextView` 就好了。
