### ISSUE TITLE
希望添加一个“关闭自动发音” 按钮功能

### ISSUE THREAD

**Issue by Mutoumiao** [Kaiyiwing/qwerty-learner#132]
必要时会优先考虑自我记忆的发音，因此需要关闭自动发音功能，再根据手动发音进行修正。谢谢

**Comment by Kaiyiwing** [comment]
![image](https://user-images.githubusercontent.com/44634134/129582845-1d87bc0c-3f87-4118-bb80-07cf488e7250.png)
