### ISSUE TITLE
建议增加外研社的单词

### ISSUE THREAD

**Issue by Mrchenged** [Kaiyiwing/qwerty-learner#134]
快中考了，平时需要背诵外研社初中年纪的英语单词，希望增加

**Comment by Kaiyiwing** [comment]
ok 我最近更新一下

**Comment by Kaiyiwing** [comment]
已更新，并添加了 人教版、外研版、北师大版的初高中词汇 af42454a3cd46a70ae43371739e7bfe2926970d8。
我暂时不会关闭这个 issues，如果有时间的话可以帮我们简单测试一下

**Comment by Mrchenged** [comment]
6666
