### ISSUE TITLE
字典选择 建议

### ISSUE THREAD

**Issue by RatChips** [Kaiyiwing/qwerty-learner#142]
每次新增词典时，可以通过获取dicts目录下的文件，自动生成字典选择界面。

字典类别、字典名称、词语数量可以存在json文件里。

**Comment by Kaiyiwing** [comment]
确实目前添加词典需要做的操作有点复杂
但考虑到算是一个低频操作，优化带来的提升不大🤔

**Comment by Happy-IT** [comment]
希望能添加自定义的字典，如果能读取只包含单词的txt文件，就能生成单词本，那样再好不过了。
不过我尝试添加已经处理好的字典，我不太清楚，也没有头绪，似乎没有生效。

**Comment by Kaiyiwing** [comment]
现在字典相关的处理确实有很多问题
目前的 pipeline 是：来自于 https://github.com/kajweb/dict 的字典通过一个本地的 python 脚本提取出 qwerty 需要的数据生成 json。 因为这个 repo 中很多数据有瑕疵，每次我都需要修改原始的数据然后重新跑一下这个脚本获得 json，然后复制到 qwerty 项目里。

同时，社区贡献新字典的流程也相对复杂。 我有想法把这两个流程都优化一下，通过 github hooks 让社区提 pr 修改字典原始数据中的错误后可以自动运行脚本并更新到 qwerty 的 repo 上
