### ISSUE TITLE
建议添加一个idea的插件

### ISSUE THREAD

**Issue by feng-wild** [Kaiyiwing/qwerty-learner#143]
建议添加一个idea的插件。相对于网页而言，插件的形式会更方便使用一些

**Comment by Kaiyiwing** [comment]
#82 
抱歉，我个人不使用 idea，暂时没有想法开发 idea 插件

**Comment by echo-LuGuang** [comment]
https://github.com/echo-LuGuang/qwerty-learner-idea

丐版，功能很少 idea版本的
