### ISSUE TITLE
下载了源代码以后，怎么才能让它在本地运行

### ISSUE THREAD

**Issue by wetery** [Kaiyiwing/qwerty-learner#152]
![image](https://user-images.githubusercontent.com/20521189/139218646-048bbd01-81c8-4c47-ae0d-bc00e9a1d7e1.png)
不会代码，能教教吗，各位大佬

**Comment by YangQing-Lin** [comment]
![image](https://user-images.githubusercontent.com/56943790/139572805-93f2a0e6-77c2-4680-80f6-81c8514629d9.png)
这个项目是只能在windows上运行的吗，我在自己本地运行成功了，想试试看能不能再服务器上也运行一个，但是发现配好环境之后依然报错，上网搜索之后也没找到解决方案

**Comment by YangQing-Lin** [comment]
![image](https://user-images.githubusercontent.com/56943790/139573019-cddf9d8d-8f15-461b-8c71-9112c6c9c2a6.png)
这是我服务器的系统版本和部分环境

**Comment by Kaiyiwing** [comment]
@YangQing-Lin 我没有在 Ubuntu 系统上测试过。  
我平时开发是在 mac 系统上，理论上也是一个类 Unix 环境，应该在 Ubuntu 是没有问题的。 

你在 `yarn start` 之前，有没有运行命令 `yarn` 安装依赖？

**Comment by YangQing-Lin** [comment]
> @YangQing-Lin 我没有在 Ubuntu 系统上测试过。 我平时开发是在 mac 系统上，理论上也是一个类 Unix 环境，应该在 Ubuntu 是没有问题的。
> 
> 你在 `yarn start` 之前，有没有运行命令 `yarn` 安装依赖？

有的，我已经先运行过yarn了，且并没有报错。我在找找看解决方法吧

**Comment by Kaiyiwing** [comment]
@YangQing-Lin 解决了嘛？ 如果解决了的话是因为什么问题导致的？

如果你只是为了在 Ubuntu 上部署这个服务的话，可以使用 `yarn build` 生成编译后的文件进行部署

**Comment by YangQing-Lin** [comment]
> @YangQing-Lin 解决了嘛？ 如果解决了的话是因为什么问题导致的？
> 
> 如果你只是为了在 Ubuntu 上部署这个服务的话，可以使用 `yarn build` 生成编译后的文件进行部署

已经解决
我发现报错内容都来自项目目录下的`node_modules`目录里，而且在作者您的仓库里并没有发现这个目录，于是我将其删除之后运行`yarn`重新生成了`node_modules`后再运行`yarn start`就成功了。
推测之前报错的原因是，我第一次运行`yarn`安装依赖是在CentOS的服务器上，运行后提示环境版本不足，于是我查资料升级版本之后再试就一直是这个报错，而Ubunut系统里的项目并不是重新clone一份，而是把CentOS里运行失败的项目直接scp过来，包括了项目目录下已经编译好的文件，所以`yarn`和`yarn start`才会失败。
惭愧的是我直到最近才解决了这个简单的问题

**Comment by Kaiyiwing** [comment]
@YangQing-Lin 感谢讲解！
对其他人运行项目也有帮助的！

**Comment by fsmox** [comment]
我这边安装的版本是由什么问题的吗？
![image](https://user-images.githubusercontent.com/46530274/144743038-0b22529e-f278-4e58-9f0e-372a141efb2c.png)
![image](https://user-images.githubusercontent.com/46530274/144743050-3d748bf9-9be6-422f-8fbf-649c8711960c.png)
报了下面的错误
![image](https://user-images.githubusercontent.com/46530274/144743074-11e54278-d399-4e6f-9ad9-085c7ec112c2.png)

**Comment by wetery** [comment]
Node.js 不要用最新的，用nvm可以把它降级到16
