### ISSUE TITLE
json格式的字典怎么编辑

### ISSUE THREAD

**Issue by wetery** [Kaiyiwing/qwerty-learner#153]
![image](https://user-images.githubusercontent.com/20521189/139259894-ae9214ff-424d-4954-adf2-73d84aa43050.png)
本来是想转成csv表格来编辑，发现转了以后再转回json格式就变了一点
![image](https://user-images.githubusercontent.com/20521189/139260241-5af99a48-64b9-4d72-8d22-3df626a0700c.png)
trans那里没有中括号了，还有音标是怎么生成的
https://blog.csdn.net/weixin_30371469/article/details/99648857
![image](https://user-images.githubusercontent.com/20521189/139262867-3e1fb7c4-7459-4652-bb83-89317839e66e.png)
翻译函数成功了，音标函数失败了

**Comment by Happy-IT** [comment]
请问，是怎么使用自己自定义的字典？
我有自定义的json文件，但我不知道在哪里添加它，也不知道将文件放到哪里。

**Comment by Kaiyiwing** [comment]
建议参考 https://github.com/Kaiyiwing/qwerty-learner/issues/40 https://github.com/Kaiyiwing/qwerty-learner/pull/67 贡献词典

**Comment by Happy-IT** [comment]
> 建议参考 #40 #67 贡献词典

感谢回答！
原来是：在.\public\dicts 里添加字典，还要在 .\src\resources\dictionary.ts 添加dictionary
我不小心把字典json格式搞错了，主界面加载一直在Lording，并没有提示，我一时半会都不知道错哪了。

**Comment by Kaiyiwing** [comment]
@Happy-IT 在 script 里面有一个 js 脚本，可以自动获取你添加字典的单词个数并更新到 dictionary.ts 里
