### ISSUE TITLE
【功能建议】发音自动切换功能

### ISSUE THREAD

**Issue by RatChips** [Kaiyiwing/qwerty-learner#158]
## 描述
希望在切换为日语词汇时，自动切换发音模式，或者添加发音切换的提示（如: 气泡提示）。

## 意义
- 利于新手（不知道发音切换）在日语等打字练习的体验。
- 长期来看，会有很多新语言（如西语等）的pr，多种语言的情况下，自动切换发音模式会十分方便。

**Comment by wetery** [comment]
我有空看看怎么搞

**Comment by Kaiyiwing** [comment]
我觉得可以在`dictionary.ts `里加一个属性代表这个词典使用的发音源
当切换字典的时候，检测一下这个属性如果声明了并且与当前使用的发音源不一致就修改成这个属性的发音源
如果未声明就不做任何操作。


这样设计，应该能兼顾当前已有的词典和日语词典的发音需求

**Comment by ArchieGu** [comment]
我觉得通过读取`dictionary.ts `中的category标签来做判断会不会更方便些，只要限定后续增加字典时在category中标注出语言即可。这样就不需要修改现有的`dictionary.ts `文件，而且也能兼顾当前多语种的使用需求。

**Comment by ArchieGu** [comment]
这是自动回复信息。
