### ISSUE TITLE
【bug】部分单词没有中文释义

### ISSUE THREAD

**Issue by 4285f4** [Kaiyiwing/qwerty-learner#159]
如题，部分单词的中文会直接显示一个 “/” ，比如考研单词的第 12 章的单词 dread ，前面的章节也有出现这种情况，但当时没记下来
<img width="960" alt="dread" src="https://user-images.githubusercontent.com/36158676/140608623-112468aa-7f6f-40e9-8cf7-80d0267e90c0.png">

**Comment by Serenasuki0a6f** [comment]
目前KaoYan_3_T.json中共有31个单词 trans为"/"

**Comment by Serenasuki0a6f** [comment]
#160 已pr
