### ISSUE TITLE
当我选用小学三年级的时候，遇到ok单词不管如何输入O都是错误的，可能是 BUG

### ISSUE THREAD

**Issue by xiaojia998** [Kaiyiwing/qwerty-learner#162]
不管如何输入，ok都是错误的，无法正确输入O这个字母

![image](https://user-images.githubusercontent.com/60349831/141417229-7452e03a-fcfc-4947-8f3c-97d2a3cc5fb4.png)
![image](https://user-images.githubusercontent.com/60349831/141417316-7f66135c-b694-4f31-ac1f-35d8c5fa55fc.png)
![image](https://user-images.githubusercontent.com/60349831/141417359-85b71e36-2103-4aac-a4c7-c2b99c198bd4.png)

**Comment by chengluyu** [comment]
确保输入的 O 是大写。比如 <kbd>Shift</kbd> + <kbd>O</kbd>。

**Comment by sdu-gyf** [comment]
经测试 `Shift`+`O`可以正常输入
