### ISSUE TITLE
 【小程序版】qwerty-learner已上线，玩法更加娱乐化（感谢@Kaiyiwing开源）

### ISSUE THREAD

**Issue by leiroc** [Kaiyiwing/qwerty-learner#173]
想分享我实现的这个小程序版打字练习，确实很感谢这个开源项目，让我有机会接入这个项目的所有词库。

一开始我只是想做一个小游戏来玩玩，后面发现这个项目的思路，打字学习英文单词，但是该项目没有手机版，所以就自己实现了一个

想体验的朋友可以微信搜：狙击单词
或者扫码体验：

![https://static.animpen.com/u/3/sniper2.jpg?_=1234](https://static.animpen.com/u/3/sniper2.jpg?_=1234)

查看演示效果点击链接： [点击查看演示效果](https://animpen.com/article/pen/sFis-2)

演示效果图：

![https://static.animpen.com/u/3/微信图片_20211229105532.jpg](https://static.animpen.com/u/3/微信图片_20211229105532.jpg)

**Comment by Kaiyiwing** [comment]
非常酷！！
在 Qwerty 之前我也有想过通过将 飞机大战和单词结合的方式 制作一个游戏化的单词记忆工具。 
「狙击单词」 这个 idea 比我的想法更适合单词记忆的场景！

**Comment by luokeke-web** [comment]
专业八级的英语单词有问题

**Comment by leiroc** [comment]
@luokeke-web 嗯，可以给这个库提issue，我会晚点更新。
