### ISSUE TITLE
feat：程序员专属词库

### ISSUE THREAD

**Issue by Kaiyiwing** [Kaiyiwing/qwerty-learner#18]
添加程序员写代码时常用的单词和命令词库

**Comment by chengluyu** [comment]
两种思路：

1. 练习代码段（code snippet），类似的网站有 [typing.io](https://typing.io)。
2. 练习代码中常见的函数名，例如 `querySelectorAll`、`sendMessage` 等。

**Comment by Kaiyiwing** [comment]
add the feat: 690bffb09e1cec9a07a2f74fbfa97ceb9edb26ad
