### ISSUE TITLE
可否增加错误修正的功能

### ISSUE THREAD

**Issue by souusei** [Kaiyiwing/qwerty-learner#181]
我在尝试使用日语这块的练习时，遇到了很多发音上的问题，输入的时候也有格式不统一，拼写错误（例如apato中出现了ā）这样的问题，如果可以的话希望可以出一个类似于错误修正的功能，即便使用者本人无法直接修改，但使用者这边提出修改建议，然后再进行修改也可以。

**Comment by sdu-gyf** [comment]
你好，我们目前都是通过手动修改词典json进行修复类似问题，最近开发者团队事情都比较多，可能无法及时解决，您可以在issue中将具体词典名，错误单词，应该改正为什么单词都提供出来。另外也欢迎您直接提pr修复问题，开发团队会统一处理。感谢使用。
