### ISSUE TITLE
建议添加高考3500词

### ISSUE THREAD

**Issue by XenonWZH** [Kaiyiwing/qwerty-learner#183]
建议添加高考3500词，利于 OIer ~~摸鱼~~ 学习英语。

**Comment by sdu-gyf** [comment]
你好，我们目前都是通过手动添加词典json，最近开发者团队事情都比较多，可能无法及时解决，欢迎您直接提pr增加词典，开发团队会统一处理。感谢使用。

**Comment by awxiaoxian2020** [comment]
already done. the issue should be closed. :)
