### ISSUE TITLE
网页收藏与开关深色模式 快捷键冲突导致无法快速收藏

### ISSUE THREAD

**Issue by dafei5350** [Kaiyiwing/qwerty-learner#184]
网页收藏与开关深色模式 快捷键冲突导致无法快速收藏，建议开关深色模式换个快捷键

**Comment by sdu-gyf** [comment]
你好，经测试在chrome浏览器下，windows(win下收藏快捷键为ctrl+d)和mac(mac下收藏快捷键为cmd+d，并无冲突)都已经屏蔽掉收藏快捷键，可以正常切换深色模式。如果需要在windows下收藏请手动收藏，辛苦！

**Comment by dafei5350** [comment]
你好，很抱歉，由于个人疏忽没有给你指明是window系统和使用的浏览器，我刚问了一下身边使用window的朋友，他们大部分收藏网页的方式为快捷键，程序员也习惯性使用键盘而不是鼠标。所以，请再次考虑（仅为个人建议）。

**Comment by tangshimin** [comment]
收藏这个行为，通常只会发生在第一次打开这个网站的时候。现在 Ctrl+D 已经成为大部分使用这个网站的用户的使用习惯了，不好改了。
