### ISSUE TITLE
Is internationalization supported?

### ISSUE THREAD

**Issue by troyeagle** [Kaiyiwing/qwerty-learner#19]
AFAIS, UI, readme, issues are only comprehensible for Chinese users. But the dictionary, especially TOEFL and IELTS, could feed any non-native speakers.

**Comment by Kaiyiwing** [comment]
That's a cooool idea, the hardest part is to find the dictionary in other languages.
This project is just start, after we add enough features, we will think about the internatianlization supported.

Thanks for your suggestion~

**Comment by chengluyu** [comment]
Hi, I’m working on this now. Thanks for your suggestion!

**Comment by cicihou** [comment]
cool idea! 
The meaning of Chinese is not really convenient
I think learning English in English may help us more :)
