### ISSUE TITLE
建议加入音量控制功能

### ISSUE THREAD

**Issue by suAmanmo** [Kaiyiwing/qwerty-learner#193]
希望能够增加音量调节功能，独立调节朗读发音与键盘输入声，避免统一使用浏览器音量设置。

**Comment by Kaiyiwing** [comment]
✨ 这个 idea 很有意义！我会加入到 todo list
因为我可预期的一段时间会忙于 春招 -> 实习 -> 秋招，在忙完这些事情后，我会进行一次比较大规模的重构和 feature 更新，预计大家期待的账号系统、进度云同步、错词分析等工具都会陆续上线～ ✨
