### ISSUE TITLE
建议有加入生词本功能

### ISSUE THREAD

**Issue by Rrrrrru** [Kaiyiwing/qwerty-learner#198]
感觉如果能弄个快捷键加入生词本重复练习就能高效背单词了，哈哈哈

**Comment by xuyixin1996** [comment]
+1

**Comment by tangshimin** [comment]
是不是这种场景：字母比较长或者语音和字母不对应，比较难记忆，所以想加入到一个单独的列表反复记忆？

**Comment by Rrrrrru** [comment]
> 是不是这种场景：字母比较长或者语音和字母不对应，比较难记忆，所以想加入到一个单独的列表反复记忆？

对呀，不认识的单词打一遍肯定记不住的，加入生词本可以针对性地重复练习
