### ISSUE TITLE
Add vocabularies of other languages

### ISSUE THREAD

**Issue by chuangli1** [Kaiyiwing/qwerty-learner#20]
能否多加入几种语言，比如中文，日文

**Comment by chengluyu** [comment]
感谢反馈问题。请问你说的是单词表的语言？还是界面语言？

**Comment by chuangli1** [comment]
单词表，联系打字嘛

**Comment by chengluyu** [comment]
感谢。我们确实有加入多语言词汇表的想法，但还没有开发。

这需要对项目进行一点重构。因为目前的设计是监听按键事件来控制打字进度，但对于中文和日文，我们需要提供文本框来捕获输入法产生的输入；同时，计算速度的方法也需要做相应调整。

如果你有更多想法或者相关经验，欢迎补充！
