### ISSUE TITLE
每个单词之后应该按空格再进入下一个

### ISSUE THREAD

**Issue by CanglongCl** [Kaiyiwing/qwerty-learner#206]
敲空格，一是没打出一个单词后普遍需要输入空格再写下一个，二是敲击空格的爽感会很棒！

**Comment by raddyyt** [comment]
> 敲空格，一是没打出一个单词后普遍需要输入空格再写下一个，二是敲击空格的爽感会很棒！

你知道为什么当年劲舞团劲乐团横行的时候网吧机器的空格键会被人故意扣掉扔垃圾桶里么
