### ISSUE TITLE
关于通过提供docker镜像文件实现本地一键部署的讨论 （欢迎有相关背景的朋友加入讨论）

### ISSUE THREAD

**Issue by RoderickChan** [Kaiyiwing/qwerty-learner#207]
RT

**Comment by Kaiyiwing** [comment]
🤔  我其实没 get 到这个需求，对于一个前端项目，如果你需要参与开发，只需要 clone 项目，然后运行下述命令
```
yarn       // 安装依赖
yarn start   // 启动开发环境
```

如果你需要打包
```
yarn  // 安装依赖
yarn build  // 打包，生成 html、js、css 等文件，直接进行静态部署即可
```

**Comment by Kaiyiwing** [comment]
因为 qwerty 是一个纯前端项目，只要支持静态部署的后端都可以部署打包后的项目。
但注意，因为我们使用了 history router，需要在后端做一些配置。

如果直接访问了首页就是访问 index.html ，此时在服务器是有匹配的，不会有 404。
前端跳转路由变化，也是前端的 history api 来控制的，和服务器没有关系。

如果直接访问了 https://xxx.com/具体的页面路径 ，此时服务器是没有匹配的资源的，就会报 404，所以需要配置服务，当 404 的时候，配置回退路由，指向 index.html，让路由在前端控制

**Comment by RoderickChan** [comment]
> 🤔 我其实没 get 到这个需求，对于一个前端项目，如果你需要参与开发，只需要 clone 项目，然后运行下述命令
> 
> ```
> yarn       // 安装依赖
> yarn start   // 启动开发环境
> ```
> 
> 如果你需要打包
> 
> ```
> yarn  // 安装依赖
> yarn build  // 打包，生成 html、js、css 等文件，直接进行静态部署即可
> ```

我是希望将部署工作放到docker image中去完成，就是说当我需要启动qwerty的时候，用制作好的镜像运行一个容器，将其监听端口映射到宿主机就能访问到服务，这样的话我不需要在本地安装yarn等环境。

**Comment by Kaiyiwing** [comment]
看社区其他人有没有想法做一个吧
我不太会用 docker （逃

**Comment by RoderickChan** [comment]
> 看社区其他人有没有想法做一个吧 我不太会用 docker （逃

我可以帮忙做一个 这个应该不难

**Comment by Kaiyiwing** [comment]
@RoderickChan https://github.com/Kaiyiwing/qwerty-learner/pull/211
有人提了一个与 docker 相关的 pr，可以尝试并测试一下（因为我不会用 docker

cc @sevenyoungairye

**Comment by sevenyoungairye** [comment]
> @RoderickChan #211 有人提了一个与 docker 相关的 pr，可以尝试并测试一下（因为我不会用 docker
> 
> cc @sevenyoungairye

服务器安装好docker和docker-compose，然后运行 `docker-compose up -d`就可以了。可以看看我的部署，我把域名贴出来。[这个是我刚刚用docker-compose部署好的。](https://ql.bitqian.cn/) @Kaiyiwing

**Comment by RoderickChan** [comment]
我有几个建议，可以一起讨论下。
1. 是不是拆成`Dockerfile`和`docker-compose.yml`两个文件更好一点，一来方便维护，二来也方便`podman`制作镜像
2. 运行权限最好还是不要使用`root`，避免引发安全问题
3. 不使用挂载，在镜像内安装`git`，通过`git clone`项目后再进行后续操作是不是更好一点，以免容器内外对项目的修改互相影响 @sevenyoungairye

**Comment by Kaiyiwing** [comment]
@sevenyoungairye 等大家对 docker 相关的讨论结束并且配置文件定型后，可以给 readme 添加 docker 章节

**Comment by sevenyoungairye** [comment]
> 我有几个建议，可以一起讨论下。
> 
> 1. 是不是拆成`Dockerfile`和`docker-compose.yml`两个文件更好一点，一来方便维护，二来也方便`podman`制作镜像
> 2. 运行权限最好还是不要使用`root`，避免引发安全问题
> 3. 不使用挂载，在镜像内安装`git`，通过`git clone`项目后再进行后续操作是不是更好一点，以免容器内外对项目的修改互相影响 @sevenyoungairye

1. 可以拆成两个文件。Dockerfile可以来构建镜像然后发布。
2. root这个不影响的，它在容器内，大不了重新启动一份镜像。这个用户数据是保存在cookie和localStorage的，数据也不会丢失。
3. 至于你说的git在镜像里面装不是不可以，但是你得把Git工具复制到容器然后安装，这样用户使用会显得太难用。如果直接安装，你得安装一堆依赖，整个镜像显得非常冗余，而且可能安装失败。不可取。

我的提议（如果是docker用户）：
1. 用户把代码克隆下来。
2. docker-compose直接编译运行项目；用docker构建并运行
3. nginx配置反向代理

**Comment by sevenyoungairye** [comment]
> 1. 关于`root`权限运行，是从权限最小化的角度来考虑的，使用`root`用户运行比使用普通用户运行的风险更高。如果不需要特权资源，一般不建议使用`root`用户运行服务。
> 2. `git`可以在构建镜像的时候通过`apt`等包管理工具下载安装，不需要手动复制。使用`git`下载的好处是宿主机不需要有`git`环境，且可以只根据提供的`dockerfile`、`docker-compose.yml`等文件构建镜像，而不需要手动下载该项目。
> 
> 我的建议是尽量把操作放在镜像构建的过程中去自动化完成，尽量少地减少用户的操作。 @sevenyoungairye

it is up to you ,what ever.I am piss up. u just do one then pr, don't be noisy to me...
