### ISSUE TITLE
奇怪的单词，无法输入

### ISSUE THREAD

**Issue by l-yxy** [Kaiyiwing/qwerty-learner#214]
在GMAT第九章，出现了一个奇怪的单词
原网站：https://qwerty.kaiyi.cool/
![image-20220511171055908](https://user-images.githubusercontent.com/68522736/167814006-4f747834-324b-4973-9c26-86989baf19f8.png)

**Comment by tangshimin** [comment]
et 和 al 之间有一个空格

**Comment by l-yxy** [comment]
> et 和 al 之间有一个空格

thanks!

**Comment by l-yxy** [comment]
good
