### ISSUE TITLE
Add other languages 

### ISSUE THREAD

**Issue by Thiago-spart** [Kaiyiwing/qwerty-learner#217]
hi I speak english and portuguese, and if it's possible, I would translate the app with i18n to have support for other languages

**Comment by Kaiyiwing** [comment]
🤔 The current codebase is not designed for i18n, and I have no idea about dictionaries and pronunciation resources about portuguese.  

But if you think the design idea of Qwerty Learner can benefit people who want to learn english through portuguese, you can feel free to fork this project and make it more suitable for you.  

And, I am thinking adding i18n to this project will benefit many English learners in different countries, so I will add it to my todos in the next reconstruction after I finish my job hunting.
