### ISSUE TITLE
kaiyiwing.github.io/qwerty-learner 网址切换不正确

### ISSUE THREAD

**Issue by s5s5** [Kaiyiwing/qwerty-learner#219]
在 kaiyiwing.github.io/qwerty-learner  换词书后，URL 变化不对，会导致刷新后404。

录了屏，可以以下链接看：
https://share.getcloudapp.com/X6uRrko9

**Comment by Kaiyiwing** [comment]
这个 bug 通过 #365 #364  基本解决了
🤔 主要因为是两个部署 baseUrl 的不同，但目前只解决了 dict 和 sound 等资源的加载问题，像是 favicon 加载还会报错，但不影响正常使用

目前使用 github/gitee pages 的用户并不多，这两个环境跟主环境的细微区别很容易测试不到， 我们也在考虑未来是否只保留主环境减少部署的复杂性
