### ISSUE TITLE
遇到中文字符无法输入

### ISSUE THREAD

**Issue by LIANGWEIBIAO** [Kaiyiwing/qwerty-learner#221]
### 1. 遇到中文的字符，无论怎么样输入都是错误
[![XYhy7t.png](https://s1.ax1x.com/2022/06/02/XYhy7t.png)](https://imgtu.com/i/XYhy7t)
GaoKao_3500.json

### 2. 建议多个单词只用空格分隔
[![XYhX3F.png](https://s1.ax1x.com/2022/06/02/XYhX3F.png)](https://imgtu.com/i/XYhX3F)

**Comment by Kaiyiwing** [comment]
🤔 可以提个 pr 修复一下

**Comment by LIANGWEIBIAO** [comment]
> 🤔 可以提个 pr 修复一下

不是很懂react

**Comment by Kaiyiwing** [comment]
直接只修改 json 中每个单词的 name 就行，不牵扯修改代码逻辑
