### ISSUE TITLE
这是BUG吗？

### ISSUE THREAD

**Issue by xly135846** [Kaiyiwing/qwerty-learner#222]
![1803B055-742E-45b6-88F6-B580E2EBAEEB](https://user-images.githubusercontent.com/30425553/171590505-c679ce29-7b3b-43ad-be72-539413863c24.png)

**Comment by Kaiyiwing** [comment]
vscode 插件版的么？ 看起来是 bug
建议移步到 https://github.com/Kaiyiwing/qwerty-learner-vscode 提 issue ba
