### ISSUE TITLE
建议添加用户制，可存储记忆进度

### ISSUE THREAD

**Issue by lzh-zone** [Kaiyiwing/qwerty-learner#223]

**Comment by Kaiyiwing** [comment]
🤔 一直有这个想法，但还在找合适的方式平衡服务器成本

**Comment by lzh-zone** [comment]
> 

好的，作者大大加油，希望早日实现哈哈哈

**Comment by lzw10168** [comment]
建议可以先出一个本地缓存的版本(*╹▽╹*)

**Comment by taneui908** [comment]
建议作者大大可以仿照anki做一个生词本, 感觉目前不用改变太多, 按现在这个页面, 点开一个词数的某一章节加两个快捷键: 秒杀(排除一些熟悉和用不到的词)和 放入生词本.  
生词本里可以像anki一样, 打完一个词有4个按钮来区别记忆深浅的程度, 并由此规划下次弹出复习的时间 (具体的算法不清楚,但也是按照艾宾浩斯曲线来的)
![image](https://user-images.githubusercontent.com/49423278/174483260-fc4e18df-06be-40df-8088-336214b228f8.png)

还有一个问题就是,我目前使用qwerty网站的方式是先听写一遍再打字一遍. 
所以操作上就需要先关闭英文英标, 打完弹出窗口选再来一遍, 此时要按ctrl+v把英文显现, 再打完之后窗口选下一章节, 这时又要按ctrl+v把英文再关掉. 
不知道有没有什么更方便的选项能解决这个问题.(其实这样打也是因为没有生词本想加深记忆的无奈之法)

目前负债不少, 之后一定给你打钱支持...

**Comment by taneui908** [comment]
> @lzw10168 我的想法差不多也是这样，最开始将相关数据文件缓存在本地，同时支持 json 格式的导入导出，让用户自己进行同步和储存，后续再加入服务器🤔

忘记@了
