### ISSUE TITLE
要國際化不？

### ISSUE THREAD

**Issue by GrimPixel** [Kaiyiwing/qwerty-learner#225]
全網沒有哪個打字軟件比這更適合學語言的了。俺一看就挺喜歡，老想把它推廣推廣。
俺認識不少詞典，有的有公衆授權。
https://polyglotclub.com/wiki/Language/Multiple-languages/Culture/Internet-Dictionaries

**Comment by Kaiyiwing** [comment]
🤔 不只是多语言字典，目前使用的字典也会有版权相关问题
但我看你发的 link 里面并没有提供版权安全的多语言字典

**Comment by GrimPixel** [comment]
那裡面有的帶 PL 標記，意為公衆授權。還有 PD，公有領域。
