### ISSUE TITLE
希望在雅思中可以增加王陆语料库的内容，比较适合机考的小伙伴

### ISSUE THREAD

**Issue by Ning-King-1** [Kaiyiwing/qwerty-learner#228]

**Comment by ggehuliang** [comment]
同在备考雅思，用的雅思王语料库。
我这边整理出来了两章的纯单词json词库自用中（对照着书自己手打的，也算是复习了hhhh），真的大赞这个工具的学习方式（尤其是VSCode摸鱼版😆）
就是不知道现在该项目接不接这种，可能和出版物有版权争议的词库贡献呢？

**Comment by 54corbin** [comment]
@ggehuliang  能分享一下你的用这种方式背语料库的心得吗？感觉效果如何？你的使用姿势是怎样的？

**Comment by Kaiyiwing** [comment]
没啥问题
根据 readme 里贡献词库的方式提 pr 就好，如果不会的话可以直接只提符合格式要求的 json 文件，我来做后续的工作
