### ISSUE TITLE
UI 改变

### ISSUE THREAD

**Issue by Kaiyiwing** [Kaiyiwing/qwerty-learner#23]
将速度显示的 ui 放置在其他位置，目前放在下方的方式影响用户阅读中文释义，过于显眼。目前的方式也影响多行中文翻译的布局

**Comment by specialjack2** [comment]
下方的统计数据,可以完全隐藏只保留两个指标, 然后再章节结束时在显示各统计指标;
另外, 统计指标的设计可以参考其他背单词的app, 个人认为目前的统计指标不够科学;
