### ISSUE TITLE
添加移动端web设计，支持响应式设计

### ISSUE THREAD

**Issue by ddy-ddy** [Kaiyiwing/qwerty-learner#232]
平时用手机用的比较多，不知道之后是否支持移动端的web呢？看作者是使用了tailwind，tailwind的响应式布局十分强大且便于设计。作者之后是否有添加移动端页面设计的想法呢？如果可以的话，希望能加入大家一起做出贡献。💪🏻

**Comment by Mahoo12138** [comment]
都使用移动端了，不如下一个记单词的app了
