### ISSUE TITLE
单词 café 中的 é 无法输入（软键盘也不行），导致无法进行下去

### ISSUE THREAD

**Issue by shunz** [Kaiyiwing/qwerty-learner#233]
如题。

建议方案：
1. 兼容输入普通的 e；
2. 增加跳过当前单词功能。

**Comment by Kaiyiwing** [comment]
有具体的 词典 和 章节 信息么？

**Comment by shunz** [comment]
> 有具体的 词典 和 章节 信息么？

en2en, Essential Words, Chapter 95

**Comment by sunnysab** [comment]
我也遇到了同样的问题，新概念英语第四册：cliché。
