### ISSUE TITLE
某些章节加载新单词的时候，网页变空白。

### ISSUE THREAD

**Issue by gaxdel** [Kaiyiwing/qwerty-learner#234]
CET-6 的 4、7、36章节 ，加载新单词的时候，网页变空白。尝试刷新、清除cookies之后还是一样。

**Comment by lonelyCZ** [comment]
我也遇到了这个问题

**Comment by Kaiyiwing** [comment]
我这边复现了这个问题
我今晚修复一下

**Comment by Kaiyiwing** [comment]
fixed by [57a9960](https://github.com/Kaiyiwing/qwerty-learner/commit/57a99604339960ad1de2a6ee25751308a7ea4d6c)
