### ISSUE TITLE
单词“a .m.” n. 午前，上午【小写】。无法输入

### ISSUE THREAD

**Issue by kingsblue** [Kaiyiwing/qwerty-learner#242]
尝试多种输入方式，如，切换大小写、添加空格，均无法实现正确输入。

单词所在章节：高考3500词 第8章

**Comment by Mahoo12138** [comment]
看了一下，字符编码是不一样（肉眼可见
+ `ａ`：Unicode编号：`U+FF41`，HTML代码：`&#65345;`
+ `a`：Unicode编号：`U+0061`，HTML代码：`&#97;`

**Comment by Kaiyiwing** [comment]
@Mahoo12138  可以直接提一个小的 pr 修改这个 typo

**Comment by Mahoo12138** [comment]
> @Mahoo12138 可以直接提一个小的 pr 修改这个 typo

没问题，不过修一下这只是解决了眼前的困难，但是词库中可能还会遇到这样的情况，如 [单词 café 中的 é 无法输入（软键盘也不行），导致无法进行下去](https://github.com/Kaiyiwing/qwerty-learner/issues/233)，就只能跳过这个章节，这很影响体验，我在想，要不要添加一个组合键跳过这个单词，继续后面的单词

**Comment by kingsblue** [comment]
使用当中还发现，浏览器其中一些“/”会合浏览器自带快捷键冲突，调整快捷键感觉也麻烦，建议设置单词跳过按钮。
