### ISSUE TITLE
能不能增加一个循环播放声音选项

### ISSUE THREAD

**Issue by flynn-eye** [Kaiyiwing/qwerty-learner#244]
本人听力渣渣  想多听几遍。。。所以可不可以加一下这个功能
我可以去提这个pr吗？

**Comment by Kaiyiwing** [comment]
目前有 `ctrl + j` 发音的功能，或许可以满足你的需求？

**Comment by flynn-eye** [comment]
> 目前有 `ctrl + j` 发音的功能，或许可以满足你的需求？

这样每次听都需要按一下按钮 `ctrl + j` ， 感觉用起来不方便。`<audio>` 标签加上 `loop` 属性就可以了

**Comment by flynn-eye** [comment]
增加一个允许循环播放的功能，我刚刚描述的不太清楚

**Comment by Kaiyiwing** [comment]
🤔 那或许可以增加一个循环播放的开关
可能主要跟其他功能和 code base 的配合

**Comment by flynn-eye** [comment]
> 🤔 那或许可以增加一个循环播放的开关 可能需要注意跟其他功能和 code base 的配合

好的  我尝试去增加这个功能
