### ISSUE TITLE
日语键位卡关了~

### ISSUE THREAD

**Issue by ellermister** [Kaiyiwing/qwerty-learner#257]
这个带声调的打不出来，也不能粘贴过关，也不知道如何跳过这个词。

![image](https://user-images.githubusercontent.com/23046078/190864906-3fad5868-50e1-48f9-bef9-f304b51beeb4.png)

应该是长音，键入 a paa to 或者 apa-to

**Comment by Kaiyiwing** [comment]
这个比较底层实现时导致的问题，目前不太好解决
在设计之初只考虑了英语作为输入语言，所以并没有考虑其他语言可能是由 多次输入或者是多个键位 去生成一个字母的情况
短期内不会解决，但会在下次重构时彻底解决

**Comment by ellermister** [comment]
@Kaiyiwing 
多个键位键入一个字母，这可能是一个问题，但对于截图里面的，应该是词库的错误，日语罗马音不应该出现带声调的字母。
所以应该是要更正词库或者无法更正词库的情况下，增加跳过按钮就行了。😊

**Comment by Kaiyiwing** [comment]
所以这个地方应该是 a 对吧
能说明一下是哪个词库的哪个章节么？

**Comment by ellermister** [comment]
N5 - Chapter 27 左右，不确定。忘记了。

正确最好应该是：`apa-to` アパート
