### ISSUE TITLE
建议打完一个单词可以停顿一下，能看到单词全貌，加深印象

### ISSUE THREAD

**Issue by Juexe** [Kaiyiwing/qwerty-learner#258]
使用隐藏单词的情况下，打完一个单词直接进入到下一个单词了，有时连猜带蒙就过去了，希望能停留一下，看看单词的全貌。

可以在隐藏单词的情况下，打完默认停顿一下，或者加个开关单词停顿？

**Comment by Kaiyiwing** [comment]
很好的建议
会增加到未来的 todo 中
