### ISSUE TITLE
如何输入 “cliché”？

### ISSUE THREAD

**Issue by riteme** [Kaiyiwing/qwerty-learner#26]
![Screenshot_20210202_135957](https://user-images.githubusercontent.com/8131974/106558710-28753300-655f-11eb-94fb-8415d19f7cdd.png)

带声调的字符我是用 compose key 输入的，但是网页上我按完 “e” 键就识别了，导致我无法打出这个单词。

**Comment by Kaiyiwing** [comment]
非常抱歉，应该是使用的开源字典的问题，我马上改一下

**Comment by Kaiyiwing** [comment]
已修复，去缓存刷新一下就可以了
