### ISSUE TITLE
可以部署到自己的服务器上么？

### ISSUE THREAD

**Issue by poshoi** [Kaiyiwing/qwerty-learner#262]
如题，有没有个人部署的方法

**Comment by silly-episode** [comment]
想拿java那一套实现一遍😁

**Comment by poshoi** [comment]
> 
不太会啊，有没有大神教一下

**Comment by Mahoo12138** [comment]
> > 
> 
> 不太会啊，有没有大神教一下

https://github.com/Kaiyiwing/qwerty-learner/blob/2defc24b2cd4f4e0ef56b00116ecce92627315a2/package.json#L51

打包以后就是静态文件，放在Web服务器即可

**Comment by poshoi** [comment]
> > > 
> > 
> > 
> > 不太会啊，有没有大神教一下
> 
> https://github.com/Kaiyiwing/qwerty-learner/blob/2defc24b2cd4f4e0ef56b00116ecce92627315a2/package.json#L51
> 
> 打包以后就是静态文件，放在Web服务器即可

不太会 有没有构建教程啥的

**Comment by Mahoo12138** [comment]
> > > > 
> > > 
> > > 
> > > 不太会啊，有没有大神教一下
> > 
> > 
> > https://github.com/Kaiyiwing/qwerty-learner/blob/2defc24b2cd4f4e0ef56b00116ecce92627315a2/package.json#L51
> > 
> > 打包以后就是静态文件，放在Web服务器即可
> 
> 不太会 有没有构建教程啥的

善用搜索引擎

**Comment by wujr5** [comment]
建议：

1、提交一个 pr 到 readme，增加说明：参与开发步骤和构建成静态文件步骤
2、如此简单的 issue 不应该反复在这里讨论，请提问者仔细研究代码（package.json）或 google 之
3、请关闭此 issue，个人关注了所有活动，主要是喜欢这个仓库，不希望被无聊的 issue 打扰
