### ISSUE TITLE
单词默写模式的一点疑问

### ISSUE THREAD

**Issue by libregd** [Kaiyiwing/qwerty-learner#27]
add this feature at 77569247fbe8ac072e3c5d2a1a216d66fd71da6

_Originally posted by @Kaiyiwing in https://github.com/Kaiyiwing/qwerty-learner/issues/8#issuecomment-771376042_

单词默写模式 == 开关英语显示 Ctrl +V对吗？
体验了一下，问题在于，plentiful 和 abundant 意思差不多，中文和英文词汇不是一一对应的关系。
建议可以考虑默写的情况下，_ _ _ _ _ _ _ _ _ 来逐一显示（每个字母对的话，绿色，还有两个差不多意思的单词字母个数都一样的情况，比如作为名词的type和kind，中文释义的话意思是差不多的。）

**Comment by Kaiyiwing** [comment]
确实会有这个问题
但目前默写模式考虑的场景是，用户完成一个章节后，用默写模式再复习这个章节（完成章节后会有默写本章的选项），所以一定程度不会太受近义词的影响。

**Comment by Kaiyiwing** [comment]
@libregd  
按照建议我也在默写模式下增加了下划线占位，一定程度上避免近义词的问题。
<img width="707" alt="CleanShot 2021-02-02 at 17 33 40@2x" src="https://user-images.githubusercontent.com/44634134/106580555-038fb880-657d-11eb-83cf-96adee0251eb.png">
