### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by yinxiangshi** [Kaiyiwing/qwerty-learner#286]
Can we add a new feature for displaying the English meaning of the words?

For example,

```
Feature
特征
```

We can switch to

```
Feature
noun. a distinctive attribute or aspect of something.
verb. have as a prominent attribute or aspect.
```

Since I know nothing about the front end works, I can not contribute to this feature myself; if someone would like to do this favor, that would be great :)

**Comment by Yangthemob** [comment]
This feature is actually related to ‘dict’, dictionary of the project, which is contributed by our users. If you have resources, you can add them into dict to help build this feature.

But I think we can make a list of wanted dictionaries to tell users what other users need and how they can contribute. Good suggestion! :)

**Comment by yinxiangshi** [comment]
I just find this on GitHub: https://github.com/matthewreagan/WebstersEnglishDictionary
Is it possible to add this dict?

**Comment by Yangthemob** [comment]
The example content looks perfect. I think we can add this if the license permits.
