### ISSUE TITLE
能帮忙加一下上海牛津初中的单词吗？

### ISSUE THREAD

**Issue by josangmi** [Kaiyiwing/qwerty-learner#293]
能帮忙加一下上海牛津初中的单词吗？
你看看附件还需要怎么调整，我来处理，谢谢了。
[上海牛津版初中英语各年级单词表.xlsx](https://github.com/Kaiyiwing/qwerty-learner/files/10195302/default.xlsx)

**Comment by Yangthemob** [comment]
这是一种参考
https://github.com/Kaiyiwing/qwerty-learner/blob/master/docs/tobuildwordbook.md

**Comment by josangmi** [comment]
我需要弄成的json文件是到具体某一个章节吗？ 比如需要到七年上Chart1吗？

<img width="674" alt="image" src="https://user-images.githubusercontent.com/46701832/208375082-3fc8ae93-24ea-4d43-9284-94f7a8c0e7ab.png">

csv文件里也只有两个字段
name | trans
单词	| [翻译]

**Comment by Yangthemob** [comment]
关于这个，您不需要手动为其分隔章节。这个任务是由程序自动完成的。

**Comment by Yangthemob** [comment]
由于章节不需要您区分，格式上已经基本没问题了。
年级是这样区分的：不同年级的内容放进单独的json文件，分别命名，然后添加到public\dicts中。
接下来，你需要在src\resources\dictionary中编辑，示例如下：
{
    id: 'japanese001',
    name: '日语常见词',
    description: '日语常用单词',
    category: '日语学习',
    url: './dicts/Japanesebasicword.json',
    length: 100,
  },
其中，id需要独一无二且具实际意义，name和description会显示给用户作为名字和描述，category决定这些词库的分类，url指向资源地址，length代表长度。
您需要手动为每个年级的文件对应添加。

**Comment by Yangthemob** [comment]
#310 
已尝试将其添加到词典
