### ISSUE TITLE
建议在README中加一个在本地部署的教程

### ISSUE THREAD

**Issue by Onlyacat233** [Kaiyiwing/qwerty-learner#296]
建议在README中加一个在本地部署的教程

**Comment by Yangthemob** [comment]
我自己的经验是yarn install然后yarn start就好

**Comment by heibaikn** [comment]
yarn && yarn start

**Comment by emilyCoding-1689** [comment]
<img width="1151" alt="image" src="https://user-images.githubusercontent.com/118091750/217259580-85f08ae1-1b49-4e20-a340-c36e1f7f46a9.png">
为什么我这边一直在爆这种错误，，，我检查了文件是没问的哇

**Comment by emilyCoding-1689** [comment]
原来是必须使用yarn才可以成功哇

**Comment by Yangthemob** [comment]
now it should be yarn & yarn run dev

**Comment by Caffeine19** [comment]
我试了下如果使用npm的话依赖安装都有问题。
另外跑npm run start的时候，node的版本貌似不能太高，我是从18切换到14。

**Comment by SHMoney2021** [comment]
各位，还是不太懂：

**Comment by SHMoney2021** [comment]
> 



> 

how? 能详细讲一下吗

**Comment by hcl666** [comment]
我不管用yarn或者yarn start都报“env: node: No such file or directory” 这是因为缺少node吗

**Comment by Caffeine19** [comment]
> 

我之前fork的是旧的webpack的版本的时候，也碰到过这个问题，然后我当时是在wsl上，把node的版本用nvm从18切换到了14，然后就没有问题了。
然后现在同步了新的fork之后，现在这个基于vite下的版本，我用node18貌似直接就可以跑。

**Comment by Caffeine19** [comment]
> 我不管用yarn或者yarn start都报“env: node: No such file or directory” 这是因为缺少node吗

你可以尝试一下用nvm切换一下node的版本先试一试
