### ISSUE TITLE
建议：增加进度记忆功能

### ISSUE THREAD

**Issue by MarvinXu** [Kaiyiwing/qwerty-learner#30]
下次打开时能从上次练习的地方开始

**Comment by Kaiyiwing** [comment]
目前会记忆上次选择的词典和章节
您的建议是增加对章节内部进度的记忆么？

**Comment by chengluyu** [comment]
> 目前会记忆上次选择的词典和章节
> 您的建议是增加对章节内部进度的记忆么？

对，参考 Typing.net，会显示之前章节的进度。
