### ISSUE TITLE
请问是否可以加入德语单词？

### ISSUE THREAD

**Issue by kb24fly** [Kaiyiwing/qwerty-learner#306]
请问是否可以加入德语单词，谢谢！

**Comment by Yangthemob** [comment]
词库目前依赖于社区贡献，加入词典的方式可以在readme中找到。如果你有推荐的德语词源，也可以在这里给出，我们可以尝试将其加入词库中~

**Comment by kb24fly** [comment]
您好因为对开发一窍不同所以没有看懂如何加入，不过词源我这里有，在附件中，麻烦您看一下
[新编1-4单词卡（全）.xlsx](https://github.com/Kaiyiwing/qwerty-learner/files/10672262/1-4.xlsx)

**Comment by kb24fly** [comment]
> 词库目前依赖于社区贡献，加入词典的方式可以在readme中找到。如果你有推荐的德语词源，也可以在这里给出，我们可以尝试将其加入词库中~

上方是分单元的，all是全部，不知道应该怎么导入比较好呢？麻烦了

**Comment by Yangthemob** [comment]
好的，我们会在近日尝试对附件处理并导入到词库中，谢谢你的贡献！

**Comment by Yangthemob** [comment]
🤔我们好奇一点：作文中文母语的人，你在学习德语的过程中，如何利用键盘输入德语呢？

是购买印有德语键位的键盘，还是使用某种软件/输入法？

这对我们适配德语有很大帮助，谢谢！

**Comment by kb24fly** [comment]
hi~抱歉才回复，用的就是普通的键盘哦，windows自带的输入法哈~
因为按shift加上一些特定的符号和字母，就可以打出德语多出来的那些字母呢~
另外有的软件会采用模糊匹配，比如德语助手~比如ss=β， a等于a: （这俩点在头上），大概就是这样了！

**Comment by kb24fly** [comment]
> 🤔我们好奇一点：作文中文母语的人，你在学习德语的过程中，如何利用键盘输入德语呢？
> 
> 是购买印有德语键位的键盘，还是使用某种软件/输入法？
> 
> 这对我们适配德语有很大帮助，谢谢！

hi抱歉才回复，用的就是普通的键盘哦，windows自带的输入法哈
因为按shift加上一些特定的符号和字母，就可以打出德语多出来的那些字母呢~
另外有的软件会采用模糊匹配，比如德语助手~比如ss=β， a等于a: （这俩点在头上），大概就是这样了！

**Comment by Yangthemob** [comment]
好的，谢谢你的反馈！
这样的话，中文学习者输入德语应该是以间接输入（依赖输入法选词）的方式，这需要对间接输入语言的支持。
我们正在尝试完善该功能，德语词典将在这之后加入。

**Comment by Kaiyiwing** [comment]
现在已经实现了 德语的beta 词典，可以简单测试下在你常用的德语输入方式是否可以使用

**Comment by kb24fly** [comment]
> 现在已经实现了 德语的beta 词典，可以简单测试下在你常用的德语输入方式是否可以使用

谢谢，已经尝试了，可以的，感谢！
