### ISSUE TITLE
默写bug

### ISSUE THREAD

**Issue by l-yxy** [Kaiyiwing/qwerty-learner#309]
https://qwerty.kaiyi.cool
完成打字后，选择默写本章节，默写完成后，选择下一章，进入下一章是默写界面，应该是学习的打字阶段。

**Comment by Yangthemob** [comment]
我个人认为这确实是逻辑设计上的失误。针对此的改动可能在近期讨论后进行。感谢你的反馈！

**Comment by TPAXcc** [comment]
> 我个人认为这确实是逻辑设计上的失误。针对此的改动可能在近期讨论后进行。感谢你的反馈！

Please do it, Thx！

**Comment by Yangthemob** [comment]
#311
