### ISSUE TITLE
能否添加黑色深色模式？

### ISSUE THREAD

**Issue by TPAXcc** [Kaiyiwing/qwerty-learner#312]
- 现在
![图片](https://user-images.githubusercontent.com/91980905/218315923-ca3ac823-6309-47ce-9460-521e273a7dd1.png)
- 预期（通过 Dark Reader）
![图片](https://user-images.githubusercontent.com/91980905/218315865-7ecb5ed1-1490-416c-8d24-29f89da9c163.png)

**Comment by Kaiyiwing** [comment]
抱歉 我没 get 到这个问题在哪？ 目前已经有 dark mode 了，上面两张截图的区别是？

**Comment by TPAXcc** [comment]
> 抱歉 我没 get 到这个问题在哪？ 目前已经有 dark mode 了，上面两张截图的区别是？

抱歉，图有点问题，我的意思是目前的深色模式是蓝黑色，能否添加一个纯黑色模式
