### ISSUE TITLE
[BUG?]当译文过长时会导致可读性降低

### ISSUE THREAD

**Issue by TPAXcc** [Kaiyiwing/qwerty-learner#313]
能否在红线处左右添加文本限制？
![图片](https://user-images.githubusercontent.com/91980905/218318084-2a313030-83cd-4e17-b089-d18739e3667e.png)

**Comment by Caffeine19** [comment]
可以考虑给译文处的div增加一个max-width属性限制一下最大的宽度应该。

**Comment by Yangthemob** [comment]
好建议！这种超长翻译的情况比较少见，我们之前确实没有考虑到这一点。

**Comment by Caffeine19** [comment]
![image](https://user-images.githubusercontent.com/108726581/218950386-5f093a80-eeb4-4a48-9baf-3e4b23f40ccf.png)
这样子看起来怎么样
max-width:56rem
删除了Translation.tsx内的text-center（靠左对齐的话，长文本读起来应该跟方便一点）。

**Comment by Kaiyiwing** [comment]
看起来还不错，方便提一个 pr 嘛

**Comment by Yangthemob** [comment]
没有text-center还是不太合适
![屏幕截图 2023-02-15 154346](https://user-images.githubusercontent.com/119289307/218964133-c62ad447-9f37-41ef-9723-f6a67b1d1da0.png)
