### ISSUE TITLE
当窗口宽度较窄时，适当的调整一下头部/header的样式

### ISSUE THREAD

**Issue by Caffeine19** [Kaiyiwing/qwerty-learner#315]
这是现在的样子
![image](https://user-images.githubusercontent.com/108726581/218655866-d0807272-8d58-415c-9f66-b52604d1a0ba.png)
这是我觉得较好的样式
![image](https://user-images.githubusercontent.com/108726581/218656001-d06bf1eb-65b0-442b-932d-89e9dd216f1a.png)

主要的修改在对于整个顶部的header加上媒体查询下的
flex-col和space-y-4
这两个样式

**Comment by Yangthemob** [comment]
好建议。确实，当前对不同尺寸屏幕的支持比较缺失，某些情况下的布局不够美观合理，需要进一步完善。

**Comment by Caffeine19** [comment]
> 好建议。确实，当前对不同尺寸屏幕的支持比较缺失，某些情况下的布局不够美观合理，需要进一步完善。

谢谢，接下来几天我试着写一下，到时候推送一下。

**Comment by Caffeine19** [comment]
![image](https://user-images.githubusercontent.com/108726581/218945746-90736f64-e14a-43f7-8f51-4037c83be965.png)
这个a标签换行之后缩进的有点奇怪（这里是由加px-*来设定内间距的），给它再加上一个“block”会比较好。
下过大概是这样
![image](https://user-images.githubusercontent.com/108726581/218947121-05ea0306-6f73-455d-9008-ad0711534103.png)

**Comment by Kaiyiwing** [comment]
下次 pr 可以试试关联 issue 的功能
https://docs.github.com/zh/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue
