### ISSUE TITLE
添加prettier-plugin-tailwind-css用于格式化tailwind的样式

### ISSUE THREAD

**Issue by Caffeine19** [Kaiyiwing/qwerty-learner#323]
npm链接:
prettier-plugin-tailwind-css
tailwind对应的文档:
https://tailwindcss.com/blog/automatic-class-sorting-with-prettier

算是在tailwind使用的时候一款很好用的插件
可以按照内置的规则整理  className=“****” 里面的一大坨东西

安装依赖后运行指令可以格式化指定的文件

**Comment by Caffeine19** [comment]
带来的其中一个好处是，如果有一些tailwind的class自己拼错了/写错了，并不包含在tailwind内置的属性中，会作为自定义样式放在 整理后的最前。
比如代码有一处写到className="text-lg opacity-45"，opacity-45并不包含在tailwind的内置选项中，会作为自定义属性，被整理成
className=“opacity-45 text-lg”

**Comment by Kaiyiwing** [comment]
🤔 或许直接提一个 pr？

**Comment by Kaiyiwing** [comment]
#329 
可以帮忙 review 一下

**Comment by Caffeine19** [comment]
> #329 可以帮忙 review 一下

好的，最近在对着代码画设计图，到时候会检查一下代码里一些样式的问题。😊

**Comment by Kaiyiwing** [comment]
> > #329 可以帮忙 review 一下
> 
> 好的，最近在对着代码画设计图，到时候会检查一下代码里一些样式的问题。😊

cooool
我看你没有留公开的邮箱，如果最近 有时间+感兴趣 去做一些小 feature 的话，方便邮件我一下嘛 me@kaiyi.cool

**Comment by Caffeine19** [comment]
> > > #329 可以帮忙 review 一下
> > 
> > 
> > 好的，最近在对着代码画设计图，到时候会检查一下代码里一些样式的问题。😊
> 
> cooool 我看你没有留公开的邮箱，如果最近 有时间+感兴趣 去做一些小 feature 的话，方便邮件我一下嘛 [me@kaiyi.cool](mailto:me@kaiyi.cool)

可以的，非常感谢！
939597201@qq.com
这是我目前常用的邮箱
