### ISSUE TITLE
单词输入bug

### ISSUE THREAD

**Issue by Hedyjing** [Kaiyiwing/qwerty-learner#324]
在高考3500词汇的55章，doesn后的 ˈ 字符不是正常的英文单引号 ‘ 字符，无法从键盘上直接输入，同时也无法复制，导致无法进行下一个单词。是否可以增加一个跳过该单词的功能。谢谢
<img width="1104" alt="image" src="https://user-images.githubusercontent.com/55574969/221086740-9e622eb3-f996-4c75-921d-ec23448cecfa.png">

**Comment by Yangthemob** [comment]
#326

**Comment by Yangthemob** [comment]
跳词功能的确应该加入。
