### ISSUE TITLE
求沪教版中考词汇表，多谢

### ISSUE THREAD

**Issue by SHMoney2021** [Kaiyiwing/qwerty-learner#327]
求沪教版中考词汇表，最好增加错题本

**Comment by Yangthemob** [comment]
词库目前来源于社区贡献。如果你有沪教版中考词汇表的文件，我们可以帮助处理并加入到词典中。

**Comment by SHMoney2021** [comment]
你好，单词表在欧路词典的在线课本，如图，但我没法导出来















在 2023-02-26 22:16:50，"Yangthemob" ***@***.***> 写道：

词库目前来源于社区贡献。如果你有沪教版中考词汇表的文件，我们可以帮助处理并加入到词典中。
