### ISSUE TITLE
自己设置词表时的length参数可以详细解释一下吗

### ISSUE THREAD

**Issue by hcl666** [Kaiyiwing/qwerty-learner#331]
目前length的意思不太清楚，能给出填写的细节吗
我的词表选择时是有的 但是选好后屏幕就只有背景 没有别的了 不知道是不是这个参数导致的

**Comment by Kaiyiwing** [comment]
length 是一个 dict 中单词的数量，可以运行 script 里的脚本自动计算

**Comment by hcl666** [comment]
运行哪个脚本呀 能提供一个demo么

**Comment by Kaiyiwing** [comment]
`scripts/update-dict-size`
你也可以提交 pr 后，我帮你设置
