### ISSUE TITLE
网站路由一旦以/gallery/开头就会触发一个无限循环的bug

### ISSUE THREAD

**Issue by hcl666** [Kaiyiwing/qwerty-learner#333]
网站路由一旦以/gallery/开头就会触发一个无限循环的bug
请求的内容会一直循环
例如“/gallery/?/&/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/ HTTP/1.1" 404 822 "http://xxxx/gallery/?/&/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/” 这就是请求的内容 这是无限循环

**Comment by Kaiyiwing** [comment]
可能是因为，我们为了让 github pages 支持 spa，使用了这个脚本 https://github.com/rafgraph/spa-github-pages
你可以在 index.html 中把相关的代码移除试一试

**Comment by hcl666** [comment]
<img width="921" alt="image" src="https://user-images.githubusercontent.com/28346798/222124445-80fb6043-869f-4e3a-a5bd-b54a267dd4d0.png">
这部分的代码我看原来就是注释掉的 目前这个问题依然存在

**Comment by Kaiyiwing** [comment]
🤔
`/gallery/` 这个表示的是寻找 `/gallery/` 路由，目前只有 `/gallery` 路由，所有会报错

**Comment by hcl666** [comment]
那这个问题该怎么解决呀 要不然建一个qq群吧

**Comment by hcl666** [comment]
我今天上午是从国内的gitee clone的代码应该不是代码没更新导致的吧

**Comment by hcl666** [comment]
我知道怎么稳定复现了
1 切换词表章节 此时路由就加上了/gallery/
2 刷新当前页面 此时立刻就会死循环

**Comment by hcl666** [comment]
大佬 希望能尽快修复呀 拜托了😭

**Comment by Kaiyiwing** [comment]
对，这个 gitee 部署的问题
因为我们使用 [rafgraph/spa-github-pages](https://github.com/rafgraph/spa-github-pages) 来让 github pages 支持 spa，但需要在 react router 初始化的时候设置 base url 为 github pages 的 base url。 我们会在 打包的时候检测是否是为了 github pages 打包，如果是则 设置 base url 为 github pages 的 base url，而 gitee pages 的部署是直接使用的 github pages 的打包结果，就没有设置正确的 base url

😂 但目前 使用 gitee pages 的用户相对较少，也没有合适的方案解决这个问题

**Comment by Kaiyiwing** [comment]
> 那这个问题该怎么解决呀 要不然建一个qq群吧

因为是开源项目，维护们也是佛系更新
所以我们可能没有精力去运营一个 qq 群

**Comment by Kaiyiwing** [comment]
不是
我们没有后端，是纯前端项目托管在 vercel

**Comment by hcl666** [comment]
这个问题我解决了 我是使用nginx部署的 在nginx站点中加如下配置即可
location = /gallery {
        rewrite ^/(gallery) /index.html permanent;
}

**Comment by hcl666** [comment]
目前我测试发现还是会有些问题
在访问不存在的地址时 依然会在后面拼接"~and~"这种内容 而且是死循环无限拼接 希望能修复

**Comment by Kaiyiwing** [comment]
现在这个 bug 应该是解决了
