### ISSUE TITLE
在完成本章的时候建议添加一个关闭按钮

### ISSUE THREAD

**Issue by hcl666** [Kaiyiwing/qwerty-learner#334]
![image](https://user-images.githubusercontent.com/28346798/222147964-6af20168-5712-4286-9d2d-2713db711a28.png)
比如在这个位置我只能刷新网页才能离开

**Comment by Kaiyiwing** [comment]
🤔 因为你完成了一个章节后，必须选择 重复本章节/下一章节 中一个选项才能回到主页面，否则主页面也不知道要加载哪一个章节

如果确实没有关闭会造成误解的话，可以加一个关闭按钮，其 onclick 函数复用 重复本章节的函数

**Comment by Kaiyiwing** [comment]
#339

**Comment by Yangthemob** [comment]
这个需求已经在 #339 中完成。如果有更多建议，可以另开issue反馈，感谢~
