### ISSUE TITLE
在默写的时候希望增加一个显示正确答案的功能

### ISSUE THREAD

**Issue by hcl666** [Kaiyiwing/qwerty-learner#338]
![image](https://user-images.githubusercontent.com/28346798/222409955-b7832497-fd2b-4e73-aa43-7b3f8c703545.png)
因为默写的时候可能这个词就是不会 想要跳过 希望增加跳过这个词的功能

**Comment by hcl666** [comment]
还有就是下面的中文意思希望放大点

**Comment by Yangthemob** [comment]
如果在默写时想要看原单词的拼写，可以点击右上角工具栏中的“小眼睛”来切换单词的显示与否。

现在跳词功能已经加入(#346 )，在同一单词连续错误四次或更多时，右上角会出现Skip按钮，点击可以跳过该词。
