### ISSUE TITLE
[todo] 增加侧边栏展示当前章节的单词列表

### ISSUE THREAD

**Issue by ChloeKurumi** [Kaiyiwing/qwerty-learner#340]
1.希望可以先通过列表背好单词
2.希望可以勾选列表中不会的单词来进行练习

**Comment by Kaiyiwing** [comment]
在主界面左侧添加一个通过 hover/click  呼出的划出框，展示本章节单词列表

基础需求： 
- 良好的 UI 设计
- 展示章节中的所有单词
- 当前练习进度

进阶需求:
1. 展示每个单词的历史练习数据
2. 通过勾选或其他操作移除不想练习的单词 （需考虑与现有 code base 的冲突，可能会有难度）

基础功能必实现，进阶需求可以根据经验和时间进行实现
