### ISSUE TITLE
一个可能比较有趣的想法，在章节总结页面对出错单词的辅助记忆

### ISSUE THREAD

**Issue by ceres0** [Kaiyiwing/qwerty-learner#345]
目前在总结页面会简单地陈列出错的单词，但是如果能展示一段根据这些单词写成的一段话可能效果会更加好一些。这个Idea是基于英语教学中的情景记忆法，以及b站一个up主尝试使用chatgpt来对一组单词创建创建一小段故事。并且在最近chatgpt的api开放之后，这个想法有了一定的可行性。但问题可能在于api是收费的，所以可以考虑作为附加内容，让用户自行准备api。

**Comment by Yangthemob** [comment]
感谢你的反馈！这个建议很好，正如你所提到的，这个特性需要一定程度的开支，因此它可能会在未来Pro版本的qwerty learner中出现。
