### ISSUE TITLE
希望增加一个可以选择不要打错一个字母就从头来的功能

### ISSUE THREAD

**Issue by hf-xz** [Kaiyiwing/qwerty-learner#347]
因为打字有错误率，可能我心里想的u，按就按成了y，这是由于我打字不熟练导致的，但现在的设置是我打错一个字就要重新来过。
希望可以加一个选项，选中后打错个字不要直接清空，而是让我自己按退格，因为实际生活中打字是不会有人给我删除整个单词的。

**Comment by Yangthemob** [comment]
我们最近在就宽容判错（判错不清空）进行讨论。宽容判错对于默写来说比较重要，因为默写有着显著较高的错误率；对于普通模式来说，清空可以认为是一种惩罚和对肌肉记忆的加强，具体是否需要宽容判错、相关ui等 还在讨论中。感谢并希望得到您更多的反馈！
