### ISSUE TITLE
部署

### ISSUE THREAD

**Issue by tradingeva** [Kaiyiwing/qwerty-learner#355]
可以在readme中分享一下部署步骤吗

**Comment by tradingeva** [comment]
yarn i 后报错00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'i'

**Comment by Kaiyiwing** [comment]
`yarn`
`yarn build`

就会打包出可部署问文件

**Comment by Kaiyiwing** [comment]
我记得有很多相关的 issue，你可以搜一下

**Comment by tradingeva** [comment]
已经解决了 yarn i 后报错00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'i'的问题 start也成功了 但貌似无法访问弄好的网页

**Comment by tradingeva** [comment]
100.26.159.74 当前无法处理此请求。
HTTP ERROR 502
