### ISSUE TITLE
总结页面也会继续计时

### ISSUE THREAD

**Issue by wetery** [Kaiyiwing/qwerty-learner#356]
![image](https://user-images.githubusercontent.com/20521189/225631653-6f9b9918-5a66-4867-bf5f-d84e508f7362.png)

**Comment by Yangthemob** [comment]
确实可复现，我也遇到了

**Comment by Yangthemob** [comment]
> 确实可复现，我也遇到了

更神奇的是，我在切换到别的网页再回到 qwerty时，它就不再计时了😂

**Comment by Kaiyiwing** [comment]
> > 确实可复现，我也遇到了
> 
> 更神奇的是，我在切换到别的网页再回到 qwerty时，它就不再计时了😂

因为失去焦点的时候会暂停

**Comment by Kaiyiwing** [comment]
> 确实可复现，我也遇到了

我这边没复现🤔

**Comment by Kaiyiwing** [comment]
很怪，我本地开发环境没办法复现，我看了下代码也没找到可能的问题🤔

**Comment by Kaiyiwing** [comment]
😂 我这边不稳定复现这个问题，没抓到大概是哪里的问题

但目前 Typing 页面的状态在多次增删后变得非常乱，我会进行一次完整的重构，估计这个 bug 也会被一起解决掉

**Comment by Kaiyiwing** [comment]
closed with #368
