### ISSUE TITLE
使用 空格键 报错

### ISSUE THREAD

**Issue by leosamxx** [Kaiyiwing/qwerty-learner#357]

**Comment by Kaiyiwing** [comment]
能具体描述一下遇到的问题么？
词典 章节 单词，以及问题的表现

**Comment by leosamxx** [comment]
Hi 你好，


昨晚开始使用五年级下第1章的时候 第一个词组 eat+ 空格键 空格键无法识别一直报错
我试了不同的电脑 也不行。


之前一直想建议这个空格键是不是可以取消掉 


 











在 2023-03-17 10:06:51，"Kaiyi" ***@***.***> 写道：

能具体描述一下遇到的问题么？
词典 章节 单词，以及问题的表现

**Comment by Kaiyiwing** [comment]
是我这边重构引入的 bug，现在已经修复，稍等片刻就会更新

**Comment by leosamxx** [comment]
Thanks











在 2023-03-17 13:55:22，"Kaiyi" ***@***.***> 写道：

是我这边重构引入的 bug，现在已经修复，稍等片刻就会更新
