### ISSUE TITLE
应该输入空格键时输入空格提示错误

### ISSUE THREAD

**Issue by MartinRocky** [Kaiyiwing/qwerty-learner#358]
![image](https://user-images.githubusercontent.com/59045109/225827967-d421ffec-28c8-45e2-aca3-c9fa59792496.png)
例如图片应该匹配ice cream，但应该输入空格时，输入空格报错，其他章节也同样如此

**Comment by Kaiyiwing** [comment]
是我这边重构引入的 bug，现在已经修复，稍等片刻就会更新
