### ISSUE TITLE
能否加入大小写模糊和标点符号开关？

### ISSUE THREAD

**Issue by TPAXcc** [Kaiyiwing/qwerty-learner#369]
现在的版本在默写的时候经常会因为句子首字母大写然后错好几次，非命令行应该不需要严格大小写，能否加入开关选择是否严格要求大小写？
另外能加入标点符号是否需要打出来的开关选择？

**Comment by Kaiyiwing** [comment]
大小写模糊在做了
忽略符号这部分我还没找到比较容易的实现路线

**Comment by Kaiyiwing** [comment]
fixed in #386 
🤔️ 我想了下，忽略符号可能不是一个全局设置需要考虑的，可能是每个字典自行决定是否放入符号
所以，就我目前的理解忽略符号暂时不会做，但未来可能会变化
