### ISSUE TITLE
考虑加入 chatgpt来辅助记忆么

### ISSUE THREAD

**Issue by LiMing11111** [Kaiyiwing/qwerty-learner#372]
<img width="880" alt="截屏2023-04-04 12 12 22" src="https://user-images.githubusercontent.com/20723102/229685447-42745dc2-c4b7-459d-8752-6638a0849d3b.png">
这是chatgpt给的建议来记住这个单词

**Comment by Kaiyiwing** [comment]
有这个计划，并进行了很多测试
但目前 API 的价格还是有点高🤔️

**Comment by LiMing11111** [comment]
让用户自己来填入api key啊，肯定是这种逻辑才对的，每个openai账户都能建自己的key。

**Comment by ringcrl** [comment]
@LiMing11111 求对应的 prompt

**Comment by TPAXcc** [comment]
> 让用户自己来填入api key啊，肯定是这种逻辑才对的，每个openai账户都能建自己的key。

普通用户 openai 官网都打不开

**Comment by nazhenhuiyi** [comment]
@LiMing11111 最近我也有个想法想尝试一下这个方向，到时欢迎你来测试和提意见。
你展示的这个是什么产品呀？
