### ISSUE TITLE
[todo] 更换冲突的 ctrl + t 快捷键

### ISSUE THREAD

**Issue by MW1Z** [Kaiyiwing/qwerty-learner#376]

**Comment by Kaiyiwing** [comment]
具体是什么操作系统和什么浏览器呢？

**Comment by TPAXcc** [comment]
> 具体是什么操作系统和什么浏览器呢？
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/113.0
Windows 10 19045.2788
成功复现

**Comment by TPAXcc** [comment]
> 具体是什么操作系统和什么浏览器呢？

具体是什么操作系统和什么浏览器呢？
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/113.0
Windows 10 19045.2788
成功复现

**Comment by TPAXcc** [comment]
> 具体是什么操作系统和什么浏览器呢？

https://support.mozilla.org/zh-CN/kb/%E9%94%AE%E7%9B%98%E5%BF%AB%E6%8D%B7%E9%94%AE
与官方快捷键<html><body>


新建标签页 | Ctrl + T
-- | --



</body>
</html>
冲突

**Comment by OBQun** [comment]
https://chromium.googlesource.com/chromium/src/+/abbfa3e92777e0b55429cac3c880f12237732385/chrome/browser/ui/browser_command_controller.cc#195
chromium及大部分浏览器把键盘最上面一排定义为系统按键阻止自定义行为
最好更换其他快捷键

**Comment by zhifanXU17** [comment]
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/113.0
Windows 11 22621.1555
同样复现
