### ISSUE TITLE
显示英文按钮的改进方案

### ISSUE THREAD

**Issue by TPAXcc** [Kaiyiwing/qwerty-learner#381]
原标题 ~~`默写模式开关英语显示后无法输入`~~
另，现在默写模式显示英语是开关，建改成按钮

**Comment by Kaiyiwing** [comment]
这个 bug 在我这没复现出来，你的操作系统和浏览器是？每次都是稳定复现么？

以及，🤔️ 没太清楚 开关和按钮的区别想表达什么，目前就是我理解的按钮？

**Comment by TPAXcc** [comment]
> 这个 bug 在我这没复现出来，你的操作系统和浏览器是？每次都是稳定复现么？
> 
> 以及，🤔️ 没太清楚 开关和按钮的区别想表达什么，目前就是我理解的按钮？

我也复现不了了，忘了当时具体还改了什么设置
我的意思是按下时显示，松开时不显示，目前在我看来更像是按钮形式的开关

**Comment by TPAXcc** [comment]
> > 这个 bug 在我这没复现出来，你的操作系统和浏览器是？每次都是稳定复现么？
> > 以及，🤔️ 没太清楚 开关和按钮的区别想表达什么，目前就是我理解的按钮？
> 
> 我也复现不了了，忘了当时具体还改了什么设置 我的意思是按下时显示，松开时不显示，目前在我看来更像是按钮形式的开关

或许可以改成悬停在按钮上面时显示英语，并且加一个50%的遮罩？

**Comment by TPAXcc** [comment]
> > > 这个 bug 在我这没复现出来，你的操作系统和浏览器是？每次都是稳定复现么？
> > > 以及，🤔️ 没太清楚 开关和按钮的区别想表达什么，目前就是我理解的按钮？
> > 
> > 
> > 我也复现不了了，忘了当时具体还改了什么设置 我的意思是按下时显示，松开时不显示，目前在我看来更像是按钮形式的开关
> 
> 或许可以改成悬停在按钮上面时显示英语，并且加一个50%的遮罩？

相当于是按下按钮的效果预览

**Comment by Kaiyiwing** [comment]
我大概明白了。你是希望在默写模式下更方便的去查看正确答案对吧🤔️

**Comment by TPAXcc** [comment]
> 我大概明白了。你是希望在默写模式下更方便的去查看正确答案对吧🤔️

是的

**Comment by Kaiyiwing** [comment]
我觉得可以在默写模式下，hover/按下 单词位置就会短暂显示正确答案

**Comment by Hemomoo** [comment]
这个需求我想做

**Comment by TPAXcc** [comment]
> 我觉得可以在默写模式下，hover/按下 单词位置就会短暂显示正确答案


但这个方式有学习成本吧，除非打开页面时弹出 Tips，或许应该两种都做？

**Comment by TPAXcc** [comment]
> 这个需求我想做

😘
