### ISSUE TITLE
章节分割的词数建议改成可调的

### ISSUE THREAD

**Issue by TPAXcc** [Kaiyiwing/qwerty-learner#382]

**Comment by Kaiyiwing** [comment]
这个在之前的 issues 中讨论过，20词一章是相对合适的长度，需要自定义这个长度的用户属于少数。 引入该设置可能会造成一些不必要的维护负担

**Comment by TPAXcc** [comment]
> 这个在之前的 issues 中讨论过，20词一章是相对合适的长度，需要自定义这个长度的用户属于少数。 引入该设置可能会造成一些不必要的维护负担

好的
