### ISSUE TITLE
vercle/github 部署

### ISSUE THREAD

**Issue by Kinvy66** [Kaiyiwing/qwerty-learner#398]
请问可以分享一下在自己的vercle或github账号的部署流程吗？

**Comment by Kaiyiwing** [comment]
vercel 的话，直接按照 vercel 引入新项目的流程就好，基本跟着引导点击下就可以了
GitHub 的话，可以看项目 github action 的配置

**Comment by Kinvy66** [comment]
> vercel 的话，直接按照 vercel 引入新项目的流程就好，基本跟着引导点几下就可以了 GitHub 的话，可以看项目 github action 的配置

将项目fork到我自己的账号，部署在vercle，vercle的配置 
![Snipaste_2023-04-17_12-38-30](https://user-images.githubusercontent.com/20577729/232379986-08e28c1a-1280-4888-b2f1-3245036933c7.png)
 部署之后访问会循环发送请求  
![Snipaste_2023-04-17_12-37-53](https://user-images.githubusercontent.com/20577729/232380003-d06247bc-bddd-4104-a0c5-da116a4f4c14.png)

**Comment by Kaiyiwing** [comment]
打包命令是 yarn build，Output Directory 是 build
