### ISSUE TITLE
个人使用体验和建议

### ISSUE THREAD

**Issue by libregd** [Kaiyiwing/qwerty-learner#4]
1. ipad+logitech蓝牙键盘可以用，这真的太妙了。
2. 下方的数据展示是必要的，但是感觉因为一直在计算，视觉上在跳动，比较影响注意力，可以考虑放到边角？——我认为这个特点是学英语，打字倒是次要的
3. 单词可否给出音标+语音（默认打开，可手动关闭）的设置，这样听力视觉二合一
4. 单词是通过输入变色的来判定输入的，可以考虑加入上一行下一行照抄的模式吗？抄对的字母绿色，不对的红色。
5. 单词可以否标明词性，如果有多个词性，从上到下排列.....
6. 单词的释义可否是中英文双语的，且可只显示某一种语言的释义，因为基本只有英语释义的才讲使用情景。
7. 想要练习文章，然后重点词汇和词组🈶️色彩高亮.....

**Comment by Kaiyiwing** [comment]
非常感谢您的建议，我们会逐步把您提出的功能添加上去～
再次感谢您的帮助

**Comment by Kaiyiwing** [comment]
我们已经在 d4b7cfef368c8c9cd3a2ea9affff804385579fc5 中添加了对音标的支持，刷新页面即可体验最新版。
再次感谢您的建议

**Comment by Kaiyiwing** [comment]
在 897e58de87ed3b6954507987815c29b352864db0 添加了开关并设置了快捷键

**Comment by libregd** [comment]
> 我们已经在 [d4b7cfe](https://github.com/Kaiyiwing/qwerty-learner/commit/d4b7cfef368c8c9cd3a2ea9affff804385579fc5) 中添加了对音标的支持，刷新页面即可体验最新版。
> 再次感谢您的建议

音标挺不错的，特别是默写模式，有音标也打开的话，基本照着写.....
感谢你们勤劳蜜蜂一样的劳模速度......

**Comment by Georgehu716** [comment]
Good idea, I think the function of word pronunciation is important.

**Comment by icheer** [comment]
考虑加入深色模式吗? 谢谢

**Comment by icheer** [comment]
默写只显示字母数量太硬核了, 是否可以加入一个"显示首字母"的选项?

**Comment by Kaiyiwing** [comment]
@icheer 这个建议非常棒，方便开一个单独的 issue 么？

**Comment by Kaiyiwing** [comment]
> 考虑加入深色模式吗? 谢谢

这个建议非常棒，方便开一个单独的 issue 么？

**Comment by icheer** [comment]
> > 考虑加入深色模式吗? 谢谢
> 
> 这个建议非常棒，方便开一个单独的 issue 么？

好的, 新开issue了

**Comment by cicihou** [comment]
特别棒的APP！尤其是发音已经在路上了，真的棒

有几个小建议，不知道会不会对于这个来说有点重
1. 单词收藏功能：对打错的单词，计入生词；开一个生词复习的模式
2. 打完之后，现在就是自动跳到下一个，可否做成一个主动切换的按钮功能；一些陌生单词敲对之后还想要看一眼
3. 解释可否考虑使用英文，更方便学英文

很棒的产品，谢谢

**Comment by chenyuheng** [comment]
很好的应用，该感谢开发者！

一点问题：我这边使用会有两个方向的滚动条，全屏也存在。改变浏览器的缩放比例到 90% 或者 110% 可以消去滚动条，但默认 100% 存在。基本不影响使用但看着难受，不知道能不能优化下。

环境：
- 浏览器 chrome 88.0.4324.150（正式版本） （64 位）
- windows 10 家庭中文版 19042.746
- 显示分辨率：1920*1080
- 系统显示的缩放：125%

截图：
![image](https://user-images.githubusercontent.com/5562899/107343617-77d9d700-6afc-11eb-822e-4529e66c4007.png)

**Comment by chengluyu** [comment]
@chenyuheng 感谢反馈，我们接下来会优化不同屏幕上的显示效果。

**Comment by StLeoX** [comment]
考虑使用上下左右键来切换吗？
比如左右切换前后单词。

**Comment by Kaiyiwing** [comment]
> 考虑使用上下左右键来切换吗？
> 比如左右切换前后单词。

暂时不会考虑，目前还是希望用户输入正确后再学习下一个单词

**Comment by anna-fan** [comment]
是否可以考虑在最上方加个进度条，比如目前一章是20个单词，能否有个1/20之类的提示？目前默写功能挺好的~

**Comment by NDS7EN** [comment]
没有记忆功能。返回键直接回到原始状态。
没有词汇量统计功能。生字模式没有。没有PASS功能。背诵模式连续错误应该加入一个自动PASS 然后把生字加入个人词典才能强化记忆。。。
总计：这个只是一个练字工具。英语都懂才用的上。基本没问题。用来学单词就算了
