### ISSUE TITLE
feat: 希望能增加 Node.js 的 API 支持

### ISSUE THREAD

**Issue by chrysalis1215** [Kaiyiwing/qwerty-learner#40]
qwerty-learner 真的是一个很棒的产品，希望后面能支持 Node.js 的API。
在前端开发中，会常常用到这些
- HTML 、CSS、 javascript、react、 vue、Node.js 等
如果有开放的词典贡献流程，可以号召更多的人去支持自己的词库，那就更棒了。

**Comment by Kaiyiwing** [comment]
很棒的建议！
我们现在还处于项目初期，目前工作在完善已有功能和增加新的功能，待到功能相对稳定后，会添加字典贡献的流程。

如果你对 nodejs api 需求比较大，又有时间贡献词典的话，可以参照 https://github.com/Kaiyiwing/qwerty-learner/blob/master/public/dicts/js-array.json 的格式，pr Nodejs Api 的字典文件，我们会完成添加到系统里的工作。

**Comment by chrysalis1215** [comment]
soga,  那我可以参与贡献词典

**Comment by sdu-gyf** [comment]
pr : #57 contributor: @chrysalis1215

**Comment by Sweetlaozhang** [comment]
什么时候能新增一个专升本的词汇？？？？

**Comment by PengChaoJay** [comment]
我可以添加一个C++ API 吗
