### ISSUE TITLE
Bug report: Abnormal shaking of icon in Header on hover

### ISSUE THREAD

**Issue by Yangthemob** [Kaiyiwing/qwerty-learner#400]
当光标移动到Header中的按钮上时，单词循环、释义显示和设置三个icon会发生异常的横向微小抖动。
在尝试debug的过程中发现，
1. 这个抖动只会发生在光标当前所处的按钮以右的按钮，比如我hover释义显示，其左侧的单词循环不会抖动，右侧的设置会抖动
2. 不是特定的icon的问题，将单词释义按钮与其紧邻右侧的英语显示按钮调换，调换后的英语显示按钮会抖动
没有发现导致抖动的原因。

**Comment by Kaiyiwing** [comment]
🤔️ 在 mac、chrome 上未复现

**Comment by Yangthemob** [comment]
原来是逆天Safari的问题......感觉修不修无所谓了🤣

**Comment by Kaiyiwing** [comment]
AKA 新 IE
