### ISSUE TITLE
用户调查

### ISSUE THREAD

**Issue by sdu-gyf** [Kaiyiwing/qwerty-learner#41]
我们对输入错误字母的时候做了三种不同的处理
1. 清空已经输入的字母并从头输入 (https://qwerty-learner.vercel.app)
2. 当遇到错误时阻塞用户输入，直到用户按下正确的字母或者按下 Backspace 删除错误的输入(https://qwerty-blocking.vercel.app/)
3. 当遇到错误时不阻塞用户输入，用户仍可以继续输入后续字母但输入错误的字母会被标记(https://qwerty-non-blocking.vercel.app/)

我们希望得到大家的反馈，我们会根据大家的反馈决定最终输入处理策略，并考虑是否三种方式并存并为用户提供切换模式选项

**Comment by jaymie9019** [comment]
我喜欢1

**Comment by wbxl2000** [comment]
对于1，这个比较推荐。可能提升体验的地方：错误后清空全部字母的时间很短暂，有时候会出现没看清不知道哪个字母输错了，会削减一些用户的耐心。或许可以在上方加一个透明度50%的历史记录 或者 在单词下面用小箭头标一下「上一次」操作的结果（即哪个字母出现了问题），感觉会更舒服一点。
对于2和3，自动清空应该是我们的一个优点？或许不应该舍弃这个，保持手感的更应该是完整的单词输入的过程，而不是也练习其中穿插如何退格的过程。（可能习惯退格的人群会有一个很短的适应期）

**Comment by KevinZonda** [comment]
倾向1，但是可以给予一个输错字母和实际字母的提示。
