### ISSUE TITLE
您好，我是一位乐高老师，可否加入spike的相关单词，语法也是python， 我这边给您提供字典

### ISSUE THREAD

**Issue by sonicdance** [Kaiyiwing/qwerty-learner#413]
除了python常用的单词，还会有一些跟乐高相关的诸如：
motor forcesensor  colorsensor
start stop
run_for_degrees run_for_rotations等这种~

**Comment by Kaiyiwing** [comment]
可以，在网站下方有我们的微信群，我们群里联系
