### ISSUE TITLE
英语显示及翻译显示在点击下一章节时不会保持状态

### ISSUE THREAD

**Issue by TPAXcc** [Kaiyiwing/qwerty-learner#417]
重复此章节时也是

**Comment by Kaiyiwing** [comment]
🤔️ 我们的理解是，英语/翻译/文字 显示都是在一个章节内需要保持的状态，切换状态应该恢复初始设置

**Comment by TPAXcc** [comment]
> 🤔️ 我们的理解是，英语/翻译/文字 显示都是在一个章节内需要保持的状态，切换状态应该恢复初始设置

或许这应该是一个选项？
