### ISSUE TITLE
[todo] 将全局 UI 设置为不可选择

### ISSUE THREAD

**Issue by TPAXcc** [Kaiyiwing/qwerty-learner#418]

**Comment by Kaiyiwing** [comment]
是全局生效的，是哪个地方没生效？

**Comment by TPAXcc** [comment]
![图片](https://user-images.githubusercontent.com/91980905/233879188-c0b33a91-cc2d-4b37-b93a-28cc35cbc2c5.png)
在我这个环境下只有打出的字母是生效的

**Comment by TPAXcc** [comment]
还是我理解错了?

**Comment by Kaiyiwing** [comment]
这个选择只适用于 单词、音标、翻译
🤔️ 你是希望所有 ui 都是关闭选择的？

**Comment by TPAXcc** [comment]
> 这个选择只适用于 单词、音标、翻译
> 🤔️ 你是希望所有 ui 都是关闭选择的？

或许这也应该是个选项，像这样:
|全局生效 Switch
|--局部生效（目前生效的部分）Switch

**Comment by Kaiyiwing** [comment]
将全局 UI 默认设置为 `user-selected: none` 以增强 UI 的完整性，需要考虑与允许用户选择 单词、释义、以及结束页面中单词的 冲突
