### ISSUE TITLE
每本字典的章节数目建议支持自定义

### ISSUE THREAD

**Issue by libregd** [Kaiyiwing/qwerty-learner#420]
- 对于简单的单词书，比如1500words，可以做到500word 完成一次练习的话，因为仅仅是复习一下。完全可以一次搞完，下方的进度条会一直暗示要做完自己给自己安排的单词数。
- 可以调整，比如第一次设置成一个章节30words，背了2章，合计 60个单词。

| chapter | 练习次数 | 正确率 |
| ------------- | ------------- | ------------- |
| 1  | 1  | (30-2)/30  |
| 2 | 1  | (30-2)/30   |

然后让我此时更改这个dict的每章words数为10的时候：

| chapter | 练习次数 | 正确率 |
| ------------- | ------------- | ------------- |
| 1  | 1  | 100%  |
| 2 | 1  | 90%   |
| 3 | 1  | 90%   |
| 4 | 1  | 100%   |
| 5 | 1  | 100%   |
| 6 | 1  | 80%   |

就是正确率会重新计算，章节数目也会改变。

**Comment by TPAXcc** [comment]
https://github.com/Kaiyiwing/qwerty-learner/issues/382
