### ISSUE TITLE
[todo] 主页面添加 Restart 按钮

### ISSUE THREAD

**Issue by TPAXcc** [Kaiyiwing/qwerty-learner#422]
可以在悬停在 Pause 按钮时弹出 Restart 按钮
建议实现为以下效果
![图片](https://user-images.githubusercontent.com/91980905/233891839-6b317c94-e796-42d7-9620-ecaa77191a66.png)

**Comment by Kaiyiwing** [comment]
我不清楚什么场景下需要这个功能？ 能简单说下你的理解么

**Comment by TPAXcc** [comment]
> 我不清楚什么场景下需要这个功能？ 能简单说下你的理解么

比如说刚打了俩单词然后不小心打错了重新开始

**Comment by Hemomoo** [comment]
是需要重新打这个章节吗

**Comment by TPAXcc** [comment]
> 是需要重新打这个章节吗
> 

是的
