### ISSUE TITLE
可以有语音吗

### ISSUE THREAD

**Issue by jaymie9019** [Kaiyiwing/qwerty-learner#44]
非常喜欢这个项目，可以在打这个单词之前播放一次这个单词发音吗，只看音标会有点难度

**Comment by sdu-gyf** [comment]
你好，感谢提议。
发音是我们在项目之初就想加上的，但发音资源相对难以获得，未来会考虑的。目前我们已经把这个功能加入 todo 里面了
相关 issue: #34 #42

**Comment by sdu-gyf** [comment]
duplicated issue
