### ISSUE TITLE
master本地部署的问题

### ISSUE THREAD

**Issue by SurvivorNo1** [Kaiyiwing/qwerty-learner#448]
开发者你好，
    我觉得这个项目很酷，所以想在本地学习一下，但我直接下载master分支代码到本地后却无法直接部署，没有正常开启服务，也没有报错。但我注释掉以下代码后，项目就能正常运行，这确实花了我一些时间去寻找原因，这是一个bug吗？我是一个前端初学者，所以如果我提出了不好的问题，还请包涵。
## code
https://github.com/Kaiyiwing/qwerty-learner/blob/8283a8d2e8d2ab170d814362ea4592185293a738/vite.config.ts#LL13C1-L15C5
https://github.com/Kaiyiwing/qwerty-learner/blob/8283a8d2e8d2ab170d814362ea4592185293a738/vite.config.ts#L37
## bad
```bash
(base) PS F:\junior_II\SoftwareDesign\qwerty-learner-master> yarn dev
yarn run v1.22.19
$ vite
Done in 0.89s.
```
## good
```bash
(base) PS F:\junior_II\SoftwareDesign\qwerty-learner-master> yarn dev
yarn run v1.22.19
$ vite
Port 5173 is in use, trying another one...

  VITE v4.1.4  ready in 763 ms

  ➜  Local:   http://127.0.0.1:5174/
  ➜  Network: use --host to expose
  ➜  press h to show help
```

**Comment by Kaiyiwing** [comment]
你的系统 和 node 版本是？

**Comment by SurvivorNo1** [comment]
> 你的系统 和 node 版本是？

谢谢回复，我的系统和node版本如下。
```bash
Windows 11 家庭中文版
```
```bash
(base) PS F:\junior_II\SoftwareDesign\qwerty-learner-master> node -v
v16.19.1
```
并且我在不注释这些代码（上面提到的）的情况下，如果我先使用了git提交到个人仓库过一次以后，就可以使用yarn dev正常开启服务。

**Comment by Kaiyiwing** [comment]
建议更新下 node js 版本

**Comment by sunxinsara** [comment]
> 

这是因为，在vite.config.ts中有获取最近一次git提交的哈希值的操作。你本地部署，可以把latestCommitHash 赋值为 local，效果也一样

**Comment by SurvivorNo1** [comment]
> > 
> 
> 这是因为，在vite.config.ts中有获取最近一次git提交的哈希值的操作。你本地部署，可以把latestCommitHash 赋值为 local，效果也一样

非常感谢，你的方法帮助我解决了这个问题。但是我觉得不够友好的是，这没有任何报错，使用--verbose运行，也没办法看见报错，我觉得至少可以抛出一个异常吧。
