### ISSUE TITLE
[todo] 修复日语语音问题

### ISSUE THREAD

**Issue by wuzhiqiao** [Kaiyiwing/qwerty-learner#456]
日语常见词里面的早上好，发音完全不对

**Comment by Kaiyiwing** [comment]
我对日语无了解

基础要求：
- 修复日语发音问题

可能会涉及到词典数据结构的改变，可以一起讨论新的数据结构

**Comment by Kaiyiwing** [comment]
related: https://github.com/Kaiyiwing/qwerty-learner/issues/285

**Comment by Kaiyiwing** [comment]
fixed in https://github.com/Kaiyiwing/qwerty-learner/pull/490
