### ISSUE TITLE
建议在项目的 readme 中添加 todo list

### ISSUE THREAD

**Issue by VectorLu** [Kaiyiwing/qwerty-learner#463]
建议在项目的 readme 中添加 todo list，或者功能开发 roadmap，让大家了解未来的功能和开发进度，以便更多的开发者和设计师参与进来。比如

### ToDo List
- [x] 更多机械键盘输入音效
- [ ] 错题本功能（预计于 20230701 完成）
- [ ] 基于艾宾浩斯记忆曲线的重复输入练习（暂未开始开发，有小伙伴愿意提交 pr 吗：）

**Comment by Kaiyiwing** [comment]
https://github.com/Kaiyiwing/qwerty-learner/blob/master/docs/CONTRIBUTING.md
在贡献方式中有写，我们会将值得做的 issues 标记为 help wanted
