### ISSUE TITLE
[todo] 数据可视化及统计页面

### ISSUE THREAD

**Issue by Kaiyiwing** [Kaiyiwing/qwerty-learner#464]
在 `src/utils/db/record.ts` 中，已经定了用户进行每个章节、每个单词练习的非常详细的数据，为可视化页面提供了数据基础

基础需求：
	- 类 github 练习热力图
	- 用户按键分布热力图
	- 用户 WPM 趋势图
	- .... 任意你认为有意义的可视化图

可参考设计：
https://www.keybr.com/profile/u3md2w6

参考可视化库：
 - Antv
 - Apache ECharts
 - ....

该页面应该做一个独立的页面，可以只实现少数可视化图表，让社区其他人逐渐贡献更多图表

**Comment by NoManPlay** [comment]
图表库有没有倾向，是否需要保持设计元素的统一

**Comment by Kaiyiwing** [comment]
🤔️ 图标库我略微倾向于使用 G2或者G2 Plot，目前看起来设计风格和文档都不错

具体到可视化页面的设计，大致配色和简洁设计的风格跟主页面类似即可

**Comment by NoManPlay** [comment]
> > 图表库有没有倾向，是否需要保持设计元素的统一
> 
> 大佬是要开发这个功能吗？？

我可能近期时间不多，你想开发可以先做

**Comment by J1aM1ng** [comment]
> 在 `src/utils/db/record.ts` 中，已经定了用户进行每个章节、每个单词练习的非常详细的数据，为可视化页面提供了数据基础
> 
> 基础需求： - 类 github 练习热力图 - 用户按键分布热力图 - 用户 WPM 趋势图 - .... 任意你认为有意义的可视化图
> 
> 可参考设计： https://www.keybr.com/profile/u3md2w6
> 
> 参考可视化库：
> 
> * Antv
> * Apache ECharts
> * ....
> 
> 该页面应该做一个独立的页面，可以只实现少数可视化图表，让社区其他人逐渐贡献更多图表

独立页面我理解类似SPA那种形式？content由打字功能切换为统计图表

**Comment by Kaiyiwing** [comment]
done
