### ISSUE TITLE
[todo] 上一个/下一个 功能

### ISSUE THREAD

**Issue by Kaiyiwing** [Kaiyiwing/qwerty-learner#465]
在练习页面，添加切换到上一个单词和下一个单词的功能

基本需求:
 - 良好的 UI 设计
 - 考虑各种可能的 corner case

**Comment by Hemomoo** [comment]
这个功能我想做

**Comment by P1ay2win** [comment]
> 这个功能我想做

开关英语显示无法应用到上一个单词和下一个单词，感觉比较影响默写时候的注意力

**Comment by Kaiyiwing** [comment]
> > 这个功能我想做
> 
> 开关英语显示无法应用到上一个单词和下一个单词，感觉比较影响默写时候的注意力

fixed in: [ff94b4e](https://github.com/Kaiyiwing/qwerty-learner/commit/ff94b4eae18cb01478774161eb9e3121e1eca8e8)
