### ISSUE TITLE
[todo] 单词自定义重复次数

### ISSUE THREAD

**Issue by Kaiyiwing** [Kaiyiwing/qwerty-learner#467]
目前已有 “单词循环” 功能，即每个单词可以练习 1 次或无数次，为了加深用户记忆，支持用户自定义每个单词的练习次数，给定几个固定的选项： 1、3、5、8、10、无限

基本需求:
 - 良好的 UI 设计
 - 考虑到各种 corner case 与现有 code base 的结合

**Comment by gxr404** [comment]
需要input自定义输入吗 还是说 上面几个固定选项就好
