### ISSUE TITLE
fix: 报告缺陷, 完成单章节词库的所有单词后, 页面白屏

### ISSUE THREAD

**Issue by icheer** [Kaiyiwing/qwerty-learner#47]
完成单章节词库的所有单词后, 例如js-global, 页面白屏, 试了两次均是如此

**Comment by Kaiyiwing** [comment]
![image](https://user-images.githubusercontent.com/44634134/107139499-84bcc600-6956-11eb-85c4-44ca0cf336d8.png)

我刚刚测试了线上的 js-global，完成一个章节后会弹出这个提示，我多次测试过每次选不同的选项均没有复现bug
建议刷新一下页面，或者更新一下浏览器版本，推荐使用 chrome 浏览器

**Comment by icheer** [comment]
> ![image](https://user-images.githubusercontent.com/44634134/107139499-84bcc600-6956-11eb-85c4-44ca0cf336d8.png)
> 
> 我刚刚测试了线上的 js-global，完成一个章节后会弹出这个提示，我多次测试过每次选不同的选项均没有复现bug
> 建议刷新一下页面，或者更新一下浏览器版本，推荐使用 chrome 浏览器

好的.. 另一个bug是, 切到js-global后刷新页面, 会提示是否继续js-global的测试, 点了"继续上次学习", 当前的单词仍然是CET-4的第一个单词cancel, 但右上角字典选择却是js-global

**Comment by Kaiyiwing** [comment]
> > ![image](https://user-images.githubusercontent.com/44634134/107139499-84bcc600-6956-11eb-85c4-44ca0cf336d8.png)
> > 我刚刚测试了线上的 js-global，完成一个章节后会弹出这个提示，我多次测试过每次选不同的选项均没有复现bug
> > 建议刷新一下页面，或者更新一下浏览器版本，推荐使用 chrome 浏览器
> 
> 好的.. 另一个bug是, 切到js-global后刷新页面, 会提示是否继续js-global的测试, 点了"继续上次学习", 当前的单词仍然是CET-4的第一个单词cancel, 但右上角字典选择却是js-global

这个bug我这边没复现出来
建议更新一下chrome版本，然后去缓存刷新一下，看看是否bug依旧

**Comment by sdu-gyf** [comment]
> > ![image](https://user-images.githubusercontent.com/44634134/107139499-84bcc600-6956-11eb-85c4-44ca0cf336d8.png)
> > 我刚刚测试了线上的 js-global，完成一个章节后会弹出这个提示，我多次测试过每次选不同的选项均没有复现bug
> > 建议刷新一下页面，或者更新一下浏览器版本，推荐使用 chrome 浏览器
> 
> 好的.. 另一个bug是, 切到js-global后刷新页面, 会提示是否继续js-global的测试, 点了"继续上次学习", 当前的单词仍然是CET-4的第一个单词cancel, 但右上角字典选择却是js-global

你好 已经复现这个 bug 会立即进行修改，感谢反馈
