### ISSUE TITLE
去除國旗繪文字

### ISSUE THREAD

**Issue by GrimPixel** [Kaiyiwing/qwerty-learner#479]
以國旗或其他旗幟代表語言，則世界多數語言無從表示。一國有多種語言；一語言於多國使用。如以一國旗指代全國語言，則國旗失去區分標示之用。

**Comment by ktKongTong** [comment]
qwerty上现有语言（包括日语、英语、德语）在其 emoji 所对应的国家都占有是事实上的优势地位或是被承认为官方语言。
>  [List of official languages by country and territory in wikipedia](https://en.wikipedia.org/wiki/List_of_official_languages_by_country_and_territory)

我认为没必要改变。如果你认为这样不好，也许你可以提出一个更好的替代方案。

> Donald Knuth: Premature optimization is the root of all evil

**Comment by GrimPixel** [comment]
國不是根据語言建的。斯瓦希里語、朝鮮語、阿拉伯語、克丘亞語，其母語者皆在多國佔多數。

常見的方法有使用該語言自稱之名。在涉及雙語時，則不能表示另一語言，此處爲漢語，故不妥。去除國旗繪文字即可。

`子貢問：「師與商也孰賢？」子曰：「師也過，商也不及。」曰：「然則師愈與？」子曰：「過猶不及。」`

**Comment by GrimPixel** [comment]
可謂『仁者見仁、智者見智』。加入國旗，在我看來則本是爲了『優化』而行。如同『天圓地方』之認知，初看有理，放之四海則不準。繪文字亦非爲知識分支而立。爲醒目而用之，於我而言，只可在內容爲該國風土人情之時。
另一分歧則是，『未雨綢繆』與『亡羊补牢』孰重孰輕。到時再變，亦無不可。
