### ISSUE TITLE
[todo] 暂停 UI 优化

### ISSUE THREAD

**Issue by ktKongTong** [Kaiyiwing/qwerty-learner#480]
当单词拼写到一半的时候，可能临时有事，切换到其他tab 页，回来时候内容重置为`按任意键开始`。
进度没有丢失，不过感觉提示可以优化，比如上方单词不隐藏，在下方添加提示： `按任意键继续`。

![scrnli_2023_5_15 22-10-37](https://github.com/Kaiyiwing/qwerty-learner/assets/44502608/2d70c2b6-08c8-4eb0-a49b-c8ec408c7d9d)

**Comment by Kaiyiwing** [comment]
对，我觉得比较合理的是 依旧显示单词，在上面有一个雾化的遮罩，遮罩上是 “按任意键继续”
