### ISSUE TITLE
use pnpm as package manager

### ISSUE THREAD

**Issue by DongHY1** [Kaiyiwing/qwerty-learner#481]
[Why use pnpm](https://pnpm.io/pnpm-vs-npm)

**Comment by ktKongTong** [comment]
As a pseudo front-end developer, I am not very clear about the differences between package managers. After briefly asking GPT, it seems that PNPM has some advantages that are worth considering.

However, I am not quite sure what the motivation would be to switch to PNPM. Is the experience with Yarn really that bad? I just checked and the size of the node_modules folder is about 600MB on Linux.

> Donald Knuth: Premature optimization is the root of all evil
