### ISSUE TITLE
[todo] import 内部排序的 lint 配置

### ISSUE THREAD

**Issue by Kaiyiwing** [Kaiyiwing/qwerty-learner#492]
目前项目使用 `@trivago/prettier-plugin-sort-imports` 实现 prettier 对多条 import 语句的自动排序，可以避免提 pr 时因为 import 顺序不同造成的 diff.

但目前对于 ` import {A, B ,C} from xxx` 中 A、B、C 的顺序没有插件进行解决，有时会在 pr 中造成不必要的diff，最好是通过配置 eslint/prettier 实现，方便在提交 commit 时由 husky 自动对代码进行处理

**Comment by mancuoj** [comment]
有一个想法，放弃 prettier，只使用 [antfu 的 eslint 配置](https://github.com/antfu/eslint-config)，反正提交 commit 都会做 lint

**Comment by OBQun** [comment]
这个问题在 #497 中解决了
