### ISSUE TITLE
隐藏右上角的工具栏，提供另一种交互方式

### ISSUE THREAD

**Issue by DongHY1** [Kaiyiwing/qwerty-learner#507]
有些用户偏好于全键盘工作流，可以考虑在设置中加一个开关，开启全键盘工作流，开启后：

- 页面右上角的工具栏将会被隐藏

- 用户可以通过快捷键，例如cmd+k的方式，弹出工具栏进行设置，可以下面这个库实现：[CMDK](https://cmdk.paco.me/)

**Comment by Hemomoo** [comment]
看着不过这个库

**Comment by Hemomoo** [comment]
看着不错啊！
