### ISSUE TITLE
日语输入以假名进行验证比较，而不是罗马字

### ISSUE THREAD

**Issue by Psermoah** [Kaiyiwing/qwerty-learner#518]
在使用日语输入时有些单词的正常输入习惯和显示在下方的罗马字不太一样。如在输入“つ”时，通常使用tu即可显示，但是在匹配罗马字时必须要输入“tsu”；以及如“番号”的罗马字显示为“bangoo”，但是在使用微软日语输入法时需要输入“banngou”才能正确显示单词。建议以假名的方式进行比对。

还有一些单词的夹名与下方显示罗马字不匹配的问题，如N2第一章中出现的“和英”发音“waei”，匹配的假名却是“和（かず）英（ひで）”。

如果可能的话，可以使用已经有对应的汉字假名显示的词典来解决吗？比如在anki中的日语单词卡组，汉字上方标有夹名，同时还有单词录音。

**Comment by AlphaBoom** [comment]
不一致的问题应该已经在这个PR里处理了：#517
关于这个问题的原因和解决方案，在这个Issue里有讨论： #496 
目前应该解决了以下问题：
* 假名和罗马字不一致
* 部分罗马字错误
---
词典质量由开发者保证着实有点困难，支持导入Anki的卡组可能是比较好的方式（改这个东西时冒出的想法）。
