### ISSUE TITLE
页面无法拦截到用户输入

### ISSUE THREAD

**Issue by zhangxiaoshang** [Kaiyiwing/qwerty-learner#52]
是这样的，我的chrome安装了插件：Vimium

当我敲击键盘时，部分键入事件应该是被Vimium拦截了，这时候页面无法获取我的输入，禁用插件后可以正常使用！

建议优化方案：页面增加一个隐藏的input输入框，默认是聚集的，用户进入页面后，输入内容时，就会是普通的输入事件，插件应该不会去拦截。

**Comment by xiaoxinw** [comment]
可以先按i进入insert mode, 我是这样解决的
