### ISSUE TITLE
There is a problem with the translation.

### ISSUE THREAD

**Issue by Noone-No** [Kaiyiwing/qwerty-learner#548]
<img width="2045" alt="image" src="https://github.com/Kaiyiwing/qwerty-learner/assets/38753227/1a0f57d9-d80b-421e-9676-02c393a4f6e9">

**Comment by Li0329** [comment]
翻译没错，可以看如下的英文解释：
![image](https://github.com/Kaiyiwing/qwerty-learner/assets/40785143/a12b4280-6f89-456b-be3a-a40494e2be82)

**Comment by Yangthemob** [comment]
我一开始也以为是翻译错了hhhhhhh
感谢 @Li0329 的检查和解释，现在应该没什么问题了。
