### ISSUE TITLE
希望能增加英文释义模式

### ISSUE THREAD

**Issue by Mickychen00** [Kaiyiwing/qwerty-learner#58]
通过回溯多年以来的个人学习经历，在学习外国语言时，能让学习者理解其英文释义，将更有助于记住这个单词的用法以及与其他近义词的不同。

**Comment by sdu-gyf** [comment]
非常感谢您的建议！
英文释义是我们在项目开始之初就想加入的功能，因为种种原因(排版，英文释义来源等)一直未进行，目前我们已经把该功能加入 todo 中了。
再次感谢您的建议

**Comment by Kaiyiwing** [comment]
duplicated with #11
