### ISSUE TITLE
小建议：过滤单词符号

### ISSUE THREAD

**Issue by Jeremy-Run** [Kaiyiwing/qwerty-learner#608]
练习过程中发现当英语单词中有空格、横线这种符号，也需要全匹配输入才能答对。但中间的符号是没必要的，可有可无。

**Comment by supermanklk** [comment]
如果是我的话，我可能认为是有个必要的功能，原因是该网站不仅面对学习英文的同学，还可以面对练习指法的同学，作为程序来说，需要键指如飞，那就要双手盲打所有键盘上的Key、大小写、功能键等~
