### ISSUE TITLE
关于单unit重复和乱序Plus的建议

### ISSUE THREAD

**Issue by lwshanbd** [Kaiyiwing/qwerty-learner#63]
可以在背每个unit之前设一个重复次数……比如这个unit我要打3遍这样的……然后每一遍的顺序是不同的

BTW 求一个python 数据挖掘有关 api

**Comment by Kaiyiwing** [comment]
这个想法不错，我们会讨论有没有可行性的，可能ui上不太好设计。

词典的话，我们主要依靠社区贡献，您有时间的话可以参照 https://github.com/Kaiyiwing/qwerty-learner/blob/master/public/dicts/js-array.json 文件贡献词典
