### ISSUE TITLE
能否增加“键盘”及“手指指示”，参考一个外国的打字练习网站

### ISSUE THREAD

**Issue by hbuxiaofei** [Kaiyiwing/qwerty-learner#65]
![111](https://user-images.githubusercontent.com/16523706/107375540-cea6d700-6b23-11eb-9614-78a96a151fe4.jpg)

打字练习网站：https://www.typingclub.com/sportal/program-3/147.play

**Comment by Kaiyiwing** [comment]
我个人觉得会影响界面的简洁，而且功能性也没有显著的增强

**Comment by chengluyu** [comment]
做起来其实挺简单，加个图和用于隐藏和显示的开关就行。但我们需要搞清楚以下问题。

* 打字练习网站加这个目的是纠正指法，这是否是我们的目的之一？
* 如果要做，我们如何找到可以免费非商业使用的这种指法演示图片？
