### ISSUE TITLE
是否可以降低提交频率？以及两个问题。

### ISSUE THREAD

**Issue by shapled** [Kaiyiwing/qwerty-learner#68]
想提个 pr，结果仓库已经更新了，刚同步到最新版，又更新了，太难了！
是否可以适当降低下提交频率，或者在 dev 分支上做？

问题如下

1. 在 windows 上开发会遇到 ```Delete `␍`  prettier/prettier``` 这样的提示
需要修改 `packages.json` 中的配置
```json
      "prettier/prettier": ["error", {
        "endOfLine": "auto"
      }]
```

2. 横纵都有滚动条（在v2上反馈过）
定位了下，是右上方 Star 按钮下的 "快捷键 Enter" 提示把元素顶出去了
我倾向在 nav 上加 padding 来解决这个问题，个人觉得有点留边也更好看

```ts
// src/components/Header/index.tsx
<nav className="w-full container mx-auto px-10 py-6">
  // ...
<nav>
```

就是把 `px-0` 改为了 `px-10`

**Comment by Kaiyiwing** [comment]
十分抱歉，因为目前在处理 github/gitee pages 对 react router 的支持性问题，要在 travis 环境下部署，所以导致提交比较频繁。目前已经解决，短期内 master 分支不会做 break change，十分抱歉。

**Comment by Kaiyiwing** [comment]
后面两个问题我马上修改一下

**Comment by Kaiyiwing** [comment]
已完成后两个问题修改，目前以 push 到 dev分支 8a433f5
