### ISSUE TITLE
能告诉后端怎么安装这个东西吗

### ISSUE THREAD

**Issue by brisk21** [Kaiyiwing/qwerty-learner#69]
一个后端看得津津有味，就是没有找到安装方法。yarn install 然并卵~~~~~

**Comment by Kaiyiwing** [comment]
首先 clone 项目，在根目录下执行 `yarn` 命令安装软件所需的包  
安装完成后，执行 `yarn start` 进入开发模式  
如果想打包部署，可以运行 `yarn build` 打包到`build`目录，可以部署到任意服务器上
