### ISSUE TITLE
建议编译一个桌面端,用Electron.百度翻译桌面端就是这样出来的

### ISSUE THREAD

**Issue by 1274365504** [Kaiyiwing/qwerty-learner#70]
使用Electron比较方便：基于前端语言开发,将现在的代码稍微改一下就行了.,跨平台，开发速度快,可以方便的通过Node.JS调用系统API、可以使用SQLite做本地字典项的缓存处理，可以将复杂的计算逻辑放在客户端进行，从而减轻服务器端的压力等等。

**Comment by Kaiyiwing** [comment]
个人感觉桌面端的意义不大，目前网页都是部署在第三方免费的服务上，没有服务器的压力。
网页端也比较符合随用随走的想法，暂时没有做一个桌面端的需求，而且Electron 打包出来的客户端也都比较大。

**Comment by 1274365504** [comment]
1、桌面端的优势是能广泛传播，一个zip，或一个exe能在各大社交平台传播文件还会留档，百度网盘也好上传。
2、让非专业人员在离线状态也能使用，没有部署门槛，不用网络。
3、有了桌面端这个仓库的访问量，关注度能提高一个量级。
4、桌面端也可以变现，加一些适当的广告。
5、这个领域确实有市场缺口。有很多大学生英语不好。本科稍微好一些，而专科的同学起个类名还用中文。变量名就是a、b、c、d。

**Comment by GrimPixel** [comment]
桌面端還是很有吸引力的，特別是在 README.MD 完全沒講如何編譯構建程序的時候。Electron 太大，那有替代品 Neutralinojs 。
在開源軟件裡打廣告這事，是要被千夫所指的。別人分叉一下就沒人理你了。
