### ISSUE TITLE
希望可以在单词下方加个键盘手指分布图

### ISSUE THREAD

**Issue by Hackergeek** [Kaiyiwing/qwerty-learner#71]
https://image.baidu.com/search/index?tn=baiduimage&ipn=r&ct=201326592&cl=2&lm=-1&st=-1&fm=result&fr=&sf=1&fmq=1613019321302_R&pv=&ic=&nc=1&z=&hd=&latest=&copyright=&se=1&showtab=0&fb=0&width=&height=&face=0&istype=2&ie=utf-8&sid=&word=%E9%94%AE%E7%9B%98%E6%89%8B%E6%8C%87%E5%88%86%E5%B8%83%E5%9B%BE

**Comment by Kaiyiwing** [comment]
duplicated with #65
