### ISSUE TITLE
要是有微信小程序就好了

### ISSUE THREAD

**Issue by 1484232791** [Kaiyiwing/qwerty-learner#73]

**Comment by g8up** [comment]
看介绍设计初衷是让 coder 能够熟悉键盘输入。
手机不是编码的主流环境。

**Comment by 1484232791** [comment]
> 看介绍设计初衷是让 coder 能够熟悉键盘输入。
> 手机不是编码的主流环境。

哈哈，只是提个建议，用它背单词也很不错啊。

**Comment by chengluyu** [comment]
感谢提议。我们有过这个想法，但还没找到一个好的形式。如果只是照搬过去，大家动力不是特别足。
