### ISSUE TITLE
能否导入生词本？

### ISSUE THREAD

**Issue by g8up** [Kaiyiwing/qwerty-learner#75]
您好，我有一款扩展是查单词的，用户生成单词本。
想配合此工具让用户练习。
是否有可能打通？比如导入单词本

**Comment by Kaiyiwing** [comment]
我们有过这个计划，但可能短期内不会提上开发日程
目前可以通过贡献词典json的方式导入用户需要的词库

**Comment by district10** [comment]
接口可以参考 geojson.io，从 url 导入词库，比如：
<http://geojson.io/#data=data:text/x-url,https%3A%2F%2Fgist.githubusercontent.com%2Fdistrict10%2F674629e19119a01a54c122b75bd59630%2Fraw%2F32b9aec619cc7e7943da6094c9a78649e522dfef%2Fbeijing.json>

我生成了一些双拼生词本，e.g.：
<https://raw.githubusercontent.com/district10/qwerty-learner-shuangpin-dicts/dev/dicts/ziranma/sample3.json>

**Comment by Kaiyiwing** [comment]
> 接口可以参考 geojson.io，从 url 导入词库，比如：
> http://geojson.io/#data=data:text/x-url,https%3A%2F%2Fgist.githubusercontent.com%2Fdistrict10%2F674629e19119a01a54c122b75bd59630%2Fraw%2F32b9aec619cc7e7943da6094c9a78649e522dfef%2Fbeijing.json
> 
> 我生成了一些双拼生词本，e.g.：
> [district10/qwerty-learner-shuangpin-dicts@`dev`/dicts/ziranma/sample3.json (raw)](https://raw.githubusercontent.com/district10/qwerty-learner-shuangpin-dicts/dev/dicts/ziranma/sample3.json)

双拼生词本很酷！
期待你的pr

**Comment by district10** [comment]
@Kaiyiwing 刚刚上线了：http://tangzhixiong.com/qwerty-learner/

可能大多数人用不着，所以不 PR 了哈哈。把词汇表解耦出去可能比较好，能够通过 url 去加载，这样用户可以自己创建自己的词汇表，但还是用你最新的 qwerty-learner。

**Comment by magictomagic** [comment]
> 您好，我有一款扩展是查单词的，用户生成单词本。
> 想配合此工具让用户练习。
> 是否有可能打通？比如导入单词本

你这个有道词典不是已经做了吗？配置改一下就好了。
不过我也有导入单词的需求。
认同【把词汇表解耦出去】

**Comment by gaoqiang19514** [comment]
> @Kaiyiwing 刚刚上线了：http://tangzhixiong.com/qwerty-learner/
> 
> 可能大多数人用不着，所以不 PR 了哈哈。把词汇表解耦出去可能比较好，能够通过 url 去加载，这样用户可以自己创建自己的词汇表，但还是用你最新的 qwerty-learner。

怎么拼接加载啊？

**Comment by Kaiyiwing** [comment]
@gaoqiang19514 目前还没有实现这个功能

**Comment by gaoqiang19514** [comment]
> @gaoqiang19514 目前还没有实现这个功能

我求你快实现

**Comment by chiakge** [comment]
希望自建生词本支持其他语言的输入法，例如日语德语等

**Comment by chengluyu** [comment]
> > @gaoqiang19514 目前还没有实现这个功能
> 
> 我求你快实现

最近大家在忙论文，没有时间设计新功能。不过欢迎提交 PR。

**Comment by chengluyu** [comment]
> 希望自建生词本支持其他语言的输入法，例如日语德语等

@chiakge 可否提供一个德语词汇表？我们需要测试一下特殊字符的输入情况。感谢。

**Comment by Kaiyiwing** [comment]
> > 希望自建生词本支持其他语言的输入法，例如日语德语等
> 
> @chiakge 可否提供一个德语词汇表？我们需要测试一下特殊字符的输入情况。感谢。

我觉得对日语德语的相关开发，可能需要一个有相关语言背景的成员参与，可能会有一些跟语言相关的问题需要解决

**Comment by chiakge** [comment]
> > > 希望自建生词本支持其他语言的输入法，例如日语德语等
> > 
> > 
> > @chiakge 可否提供一个德语词汇表？我们需要测试一下特殊字符的输入情况。感谢。
> 
> 我觉得对日语德语的相关开发，可能需要一个有相关语言背景的成员参与，可能会有一些跟语言相关的问题需要解决
找不到json格式的单词本

**Comment by Kaiyiwing** [comment]
目前生词本是存储在 `./public/dicts/` 中
