### ISSUE TITLE
语言修改为lang=zh-Hans?

### ISSUE THREAD

**Issue by icheer** [Kaiyiwing/qwerty-learner#78]
现在lang=en, 中文系统的浏览器会提示翻译为中文, 界面里的单词会变成乱码, 何不修改lang=zh-Hans? 这是个中文网站呀

p.s. 深色模式有了, 很赞, 感谢!

**Comment by Kaiyiwing** [comment]
应该是使用 cra 是没注意修改，我马上修改一下
