### ISSUE TITLE
换个favicon?

### ISSUE THREAD

**Issue by icheer** [Kaiyiwing/qwerty-learner#79]
现在的favicon.ico是react的logo, 何不换个自己的(键盘?)logo?

**Comment by icheer** [comment]
另外在这里夹带的issue可以吗?  现在每个字母输对变绿输错变红的动画过程比较慢, 反馈有点滞后肉肉的感觉, 看了css是0.3秒, 可以缩短一些吗?

**Comment by Kaiyiwing** [comment]
> 另外在这里夹带的issue可以吗? 现在每个字母输对变绿输错变红的动画过程比较慢, 反馈有点滞后肉肉的感觉, 看了css是0.3秒, 可以缩短一些吗?

那个 300ms 是用户输错后，抖动特效的持续时间

**Comment by Kaiyiwing** [comment]
> 现在的favicon.ico是react的logo, 何不换个自己的(键盘?)logo?

目前免费的没找到太合适的
如果遇到合适的，可以推荐一下～

**Comment by icheer** [comment]
> > 另外在这里夹带的issue可以吗? 现在每个字母输对变绿输错变红的动画过程比较慢, 反馈有点滞后肉肉的感觉, 看了css是0.3秒, 可以缩短一些吗?
> 
> 那个 300ms 是用户输错后，抖动特效的持续时间

我在控制台里把.3s改成0.01s和1s分别试了一下, 确认这个是字体和背景颜色的transition-duration,  如果改成1s, 变绿变红会变得更肉, 改成0s就会很干脆, 而且也没影响输错时的抖动特效..

**Comment by Kaiyiwing** [comment]
> > > 另外在这里夹带的issue可以吗? 现在每个字母输对变绿输错变红的动画过程比较慢, 反馈有点滞后肉肉的感觉, 看了css是0.3秒, 可以缩短一些吗?
> > 
> > 
> > 那个 300ms 是用户输错后，抖动特效的持续时间
> 
> 我在控制台里把.3s改成0.01s和1s分别试了一下, 确认这个是字体和背景颜色的transition-duration, 如果改成1s, 变绿变红会变得更肉, 改成0s就会很干脆, 而且也没影响输错时的抖动特效..

我检查了一下，确实之前添加了 300ms 的动画，已经移除了 8ccab30

**Comment by icheer** [comment]
> > > > 另外在这里夹带的issue可以吗? 现在每个字母输对变绿输错变红的动画过程比较慢, 反馈有点滞后肉肉的感觉, 看了css是0.3秒, 可以缩短一些吗?
> > > 
> > > 
> > > 那个 300ms 是用户输错后，抖动特效的持续时间
> > 
> > 
> > 我在控制台里把.3s改成0.01s和1s分别试了一下, 确认这个是字体和背景颜色的transition-duration, 如果改成1s, 变绿变红会变得更肉, 改成0s就会很干脆, 而且也没影响输错时的抖动特效..
> 
> 我检查了一下，确实之前添加了 300ms 的动画，已经移除了 [8ccab30](https://github.com/Kaiyiwing/qwerty-learner/commit/8ccab30f1658437d27fdc8e39625cdae74981dcb)

谢谢 看到已经是0.15s了  体验比之前好很多

**Comment by Kaiyiwing** [comment]
@icheer 我设置成 0ms 了，你感受一下区别
还是设置成100ms左右合适

**Comment by icheer** [comment]
> @icheer 我设置成 0ms 了，你感受一下区别
> 还是设置成100ms左右合适？

我个人觉得0秒无动画挺好的, 可以综合考虑下其他用户的意见 ^_^

**Comment by Kaiyiwing** [comment]
closed with #100
