### ISSUE TITLE
关于下一阶段计划的问题

### ISSUE THREAD

**Issue by qs2d** [Kaiyiwing/qwerty-learner#80]
请问有下一阶段计划吗？
可以让非前端的人也能参与进来。

**Comment by Kaiyiwing** [comment]
目前还没有明确的计划，如果你有想法可以提出来一起讨论🤔

**Comment by qs2d** [comment]
建议增加版本包发布，支持本地安装
增加开发模式，快速搭建开发环境

**Comment by Kaiyiwing** [comment]
开发模式？ 目前 clone 项目 使用 yarn 安装依赖即可运行

**Comment by LinkXSystem** [comment]
请问是否可以有计划支持基于 electron 的客户端离线版本？

**Comment by Kaiyiwing** [comment]
> 请问是否可以有计划支持基于 electron 的客户端离线版本？

在 #70  有过讨论，目前还是觉得没有特别大的必要去做离线版本

**Comment by chengluyu** [comment]
欢迎自己尝试！但这个项目的 contributors 暂时没有这个想法。主要出于下面几个原因。

1. 我们并没有时间花若干天去读 Electron 文档、适配 Electron 环境并优化体验。
2. 离线使用有非常简单的替代方案——克隆项目、安装依赖、构建项目、用 [serve](https://www.npmjs.com/package/serve) 或者 [http.server](https://docs.python.org/3/library/http.server.html) 在本机 host，你甚至可以把它做成系统服务。

**Comment by LinkXSystem** [comment]
@chengluyu 是否可以 Projects 里面对开发计划进行管理。因为我想参与到此项目的开发中的话，目前也不清楚，需要什么功能，怎么领取

**Comment by Kaiyiwing** [comment]
> @chengluyu 是否可以 Projects 里面对开发计划进行管理。因为我想参与到此项目的开发中的话，目前也不清楚，需要什么功能，怎么领取
> 
> 

我会尽快在 Projects 里整理开发计划，目前可以领取 Issue 中标记为 Help Wanted 的工作，并在有一定进展后提交 draft pr ，方便讨论。感谢贡献

**Comment by jnchen** [comment]
建议加入不同配列,dvorak colemak workman这种

**Comment by chengluyu** [comment]
> 建议加入不同配列,dvorak colemak workman这种

建议开一个新 issue 具体描述。感谢。
