### ISSUE TITLE
建议增加重复次数设定和例句

### ISSUE THREAD

**Issue by zhz** [Kaiyiwing/qwerty-learner#81]
好玩，提两个小建议：

1. 适当重复可以提高记忆效果
只拼写对一次就切换到下一个单词，对于生疏词汇记忆效果不佳，建议可以人工设置重复次数或者根据 错误情况/打字速度等 自动调整重复次数。

2. 情景例句可以增加记忆效果
如有可能，建议在音标、解释、发音基础上再增加个可选的例句显示。对于程序员字典，例句可以是简短的示例代码。

**Comment by Kaiyiwing** [comment]
感谢支持～
第一个建议我觉得可行性很大，一次拼写确实不能保证记忆强度。
第二个的话，目前得到反馈显示，用户在拼写时大多将注意力集中在单词上，对翻译的注意力相对较少。所以目前不太考虑增加更多需要用户关注的信息。
