### ISSUE TITLE
Request for IDEA plugin

### ISSUE THREAD

**Issue by sorryyyyy** [Kaiyiwing/qwerty-learner#82]
vscode插件都有了，不知道idea的插件会不会出生。

**Comment by Kaiyiwing** [comment]
我可能不会写，因为不太用 idea
有兴趣的可以参照 vscode 插件的代码实现一下，我可以放到两个项目文档中帮忙宣传

**Comment by chengluyu** [comment]
[IDEA 插件开发参考](https://plugins.jetbrains.com/docs/intellij/getting-started.html)——擅长写 Java 或者 Kotlin 的同学可以参考一下。

**Comment by qbosen** [comment]
好东西，等有时间了可以研究下，想写IDEA插件很久了

**Comment by echo-LuGuang** [comment]
https://github.com/echo-LuGuang/qwerty-learner-idea

丐版，功能很少 idea版本的
