### ISSUE TITLE
键盘手势支持

### ISSUE THREAD

**Issue by shaodahong** [Kaiyiwing/qwerty-learner#83]
感谢这么好的项目

实际使用完全足够，但是要是能有键盘手势支持就会更好了（哪个手指应该按什么键），这样也可以帮忙矫正和纠错

**Comment by Kaiyiwing** [comment]
这个之前有 Issue 讨论过，简单总结下 我们认为项目核心聚焦在单词记忆而不是指法练习，更多讨论参考 #65
