### ISSUE TITLE
关于『错题本』『记忆模式』等功能的建议

### ISSUE THREAD

**Issue by XhinLiang** [Kaiyiwing/qwerty-learner#85]
本项目其实现在是基于纯前端来实现的，如果要加入『错题本』『记忆模式』等功能，最直观的想法就是引入一个账户系统。
但引入账户系统其实会带来很多的工作量，比如手机号验证，账号密码存储等。

我觉得所有的数据，可以用一个 JSON 文件存储。比如我这次练习之后，数据可以存储在 localStorage，用户可以选择清空，或者导出 JSON 文件到本地，也可以选择导入一个 JSON 文件继续游戏。这样就能省去了后端的开发工作，同时也能快速支持这些功能。

后续如果有更多的需求，确实需要引入后端的，后端的存储其实也可以复用这些 JSON 数据结构。

**Comment by XhinLiang** [comment]
如果只存储生词
---
假设平均一个单词 10 个字母，使用 UTF-8 编码，一个字母仅需 1 个字节。存储一个单词需要 10 个字节，再加上 JSON 本身冗余的符号『"something",』 ，算一个单词 15 个字节。
一个词典最多 2w 个单词，如果错过的词有 5000 个，那么存储一个词典的错题一般只需要  5000 * 15 个字节，也就是 75k。
如果词典错题分开 JSON 存储，基本上没压力。所有词典的错题都放一个 JSON 存储，基本上也不会超过 1M。

如果既存储生词，也存储上次背诵的时间
---
需要额外一个秒级别的时间戳，额外一个 int 再加上一些冗余的符号，一个单词需要 15 + 10 个字节，那么单个词典的生词存储就变成 125k 左右了。

**Comment by JinChengneng** [comment]
试用了一下觉得确实比较需要背单词模式和错题本

**Comment by Kaiyiwing** [comment]
没有特别理解『记忆模式』是指？

**Comment by JinChengneng** [comment]
> 没有特别理解『记忆模式』是指？

我的理解是根据[艾宾浩斯遗忘曲线](https://www.wikiwand.com/zh-hans/%E9%81%97%E5%BF%98%E6%9B%B2%E7%BA%BF)设计的背单词模式。这样能一边练打字一边背单词，会更有吸引力一些，我体验了半个小时纯打字，感觉有点枯燥了。

**Comment by Kaiyiwing** [comment]
@JinChengneng 
我个人的想法是这样的：

设计时背单词模式为 
“完成一个 chapter -> 进入默写模式 重复该 chapter -> 普通模式 -> 默写模式”
直至对该 chapter 记忆较为深刻，再继续下一 chapter。该过程的核心是将肌肉记忆与单词的中英连结起来。

『错题本』可能是有意义的功能，但我个人对 艾宾浩斯遗忘曲线 不是特别感冒，其原始论文是基于记忆无意义文字绘制的记忆曲线，对单词类的记忆只能说有借鉴作用。本项目更多针对肌肉记忆的养成，所以是否引入记忆模式(这需要对系统改变较大)需要更多的讨论。

**Comment by JinChengneng** [comment]
> @JinChengneng
> 我个人的想法是这样的：
> 
> 设计时背单词模式为
> “完成一个 chapter -> 进入默写模式 重复该 chapter -> 普通模式 -> 默写模式”
> 直至对该 chapter 记忆较为深刻，再继续下一 chapter。该过程的核心是将肌肉记忆与单词的中英连结起来。
> 
> 『错题本』可能是有意义的功能，但我个人对 艾宾浩斯遗忘曲线 不是特别感冒，其原始论文是基于记忆无意义文字绘制的记忆曲线，对单词类的记忆只能说有借鉴作用。本项目更多针对肌肉记忆的养成，所以是否引入记忆模式 (这需要对系统改变较大) 需要更多的讨论。

感谢回复，我明白您的想法。但我在使用中碰到的问题是，一个 chapter 中往往是不同难度的单词同时出现的，或许我们可以调整一下默写模式，增加出错单词出现的频率，降低未出错单词出现的频率，不知道这样会不会使得默写模式更合理。

**Comment by Kaiyiwing** [comment]
@JinChengneng 
或许一个可能的想法是『错题本背诵模式』，我们记录用户出错的单词和频率，用户可以在一段时间后查看错题记录和针对错题进行练习与背诵

**Comment by JinChengneng** [comment]
> @JinChengneng
> 或许一个可能的想法是『错题本背诵模式』，我们记录用户出错的单词和频率，用户可以在一段时间后查看错题记录和针对错题进行练习与背诵

很好的想法，期待这个功能的实现！

**Comment by XhinLiang** [comment]
> @JinChengneng
> 或许一个可能的想法是『错题本背诵模式』，我们记录用户出错的单词和频率，用户可以在一段时间后查看错题记录和针对错题进行练习与背诵

主要是现在我并不知道我完成过哪些 chapter，需要自己记下来。
