### ISSUE TITLE
建议加入不同键盘配列的学习

### ISSUE THREAD

**Issue by jnchen** [Kaiyiwing/qwerty-learner#87]
dvorak colemak workman等等

**Comment by Kaiyiwing** [comment]
如果是指针对不同键盘布局学习的话，与本项目的目标不太符合，可以尝试一下市面上比较常见的 typing 练习工具，都有选择键盘布局的功能。

**Comment by chengluyu** [comment]
请问您在日常使用中是专门购买了这样的键盘？还是在系统中设置了相应的键盘布局？以及软件上如何改善可以帮到您呢？

**Comment by jnchen** [comment]
> 请问您在日常使用中是专门购买了这样的键盘？还是在系统中设置了相应的键盘布局？以及软件上如何改善可以帮到您呢？

是系统中设置了键盘布局，然后用qwerty多年，不太好切换，所以希望能有一个工具

**Comment by chengluyu** [comment]
> > 请问您在日常使用中是专门购买了这样的键盘？还是在系统中设置了相应的键盘布局？以及软件上如何改善可以帮到您呢？
> 
> 是系统中设置了键盘布局，然后用qwerty多年，不太好切换，所以希望能有一个工具

不知道我的理解对不对：系统中的键盘布局在输入法层面起作用，因为我们现在捕获的是按键事件而不是文字输入事件，所以输入的仍然是 QWERTY 布局。

**Comment by chengluyu** [comment]
我觉得应该比较好解决，在输入的时候加入一套 mapping 就好了。

**Comment by Kaiyiwing** [comment]
> > > 请问您在日常使用中是专门购买了这样的键盘？还是在系统中设置了相应的键盘布局？以及软件上如何改善可以帮到您呢？
> > 
> > 
> > 是系统中设置了键盘布局，然后用qwerty多年，不太好切换，所以希望能有一个工具
> 
> 不知道我的理解对不对：系统中的键盘布局在输入法层面起作用，因为我们现在捕获的是按键事件而不是文字输入事件，所以输入的仍然是 QWERTY 布局。

目前捕获的是键盘事件，但最终还是通过`keydown`事件中获取的`e.key`属性，其为键盘输入后实际的打印字符而不是`KeyCode`,按我的理解是对任意键盘排列都是有效的。

https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key

**Comment by chengluyu** [comment]
我在 macOS 上配置了德沃夏克布局，确实如 @Kaiyiwing 所说，`e.key` 拿到的已经是在德沃夏克布局下对应的字符。

@jnchen 可否透露您所使用的操作系统和设置键盘布局所进行的操作？
