### ISSUE TITLE
feat: 句子背诵模式

### ISSUE THREAD

**Issue by Kaiyiwing** [Kaiyiwing/qwerty-learner#9]

**Comment by lengthmin** [comment]
句子可以从一些现有的英文语料库中取，比如 nltk 的数据：https://github.com/nltk/nltk_data

还可以加入文章模式

**Comment by Kaiyiwing** [comment]
@lengthmin 非常感谢您的建议，我们在完善单词模式后，会着手添加英语文章的练习部分
