### ISSUE TITLE
省略号

### ISSUE THREAD

**Issue by frilxy** [Kaiyiwing/qwerty-learner#92]
请问一下这种省略号怎么打：
![image](https://user-images.githubusercontent.com/41298432/109971150-dfb4c380-7d30-11eb-8940-34306c51811e.png)

**Comment by Kaiyiwing** [comment]
这个是估计是未将省略号添加到正则中，我会尽快修复

**Comment by Kaiyiwing** [comment]
fixed at 4a79f95
