### ISSUE TITLE
qwerty-learner现在是没有用的项目

### ISSUE THREAD

**Issue by Pantyhose-X** [Kaiyiwing/qwerty-learner#99]
我有一个好想法 你可以做成一个 监听输入法工具，应用于学习语言，这样可以纠正发音和加深记忆，调用文本转语音TTS 朗读输入单词或句子。 `输入空格` 后TTS朗读单词，`输入空格`10秒后朗读句子。
你可以内置 [mozilla文字转语音](https://github.com/mozilla/TTS) 或调用Win10内置的或调用Win10安装的
>
`视频例子`https://www.youtube.com/watch?v=YPBn6D6pf78&feature=youtu.be&t=213
>
Android或 iOS 你可以做成输入法，你可以基于[OpenBoard](https://github.com/dslul/openboard)或[Simple Keyboard](https://github.com/rkkr/simple-keyboard)、内置mozilla文字转语音或调用google文本转语音TTS。
>
不以英语为母语的人都需要学习英语，市场非常广

**Comment by chengluyu** [comment]
Hi, we’re glad to hear from you! The translation does not very make sense to us. Would you like to rephrase your issue in English?

**Comment by chengluyu** [comment]
Closed due to unresponsiveness for more than 30 days. Feel free to re-open if you can provide more information. 😅

**Comment by Pantyhose-X** [comment]
> Closed due to unresponsiveness for more than 30 days. Feel free to re-open if you can provide more information. 😅

我有一个好想法 你可以开发一个 监听输入法工具，应用于学习语言，这样可以纠正发音和加深记忆，调用文本转语音TTS 朗读输入单词或句子。 `输入空格` 后TTS朗读单词，`输入空格`10秒后朗读句子。
你可以内置 [mozilla文字转语音](https://github.com/mozilla/TTS) 或调用Win10内置的或调用Win10安装的
>
`视频例子`https://www.youtube.com/watch?v=YPBn6D6pf78&feature=youtu.be&t=213
>
Android或 iOS 你可以做成输入法，你可以基于[OpenBoard](https://github.com/dslul/openboard)或[Simple Keyboard](https://github.com/rkkr/simple-keyboard)、内置mozilla文字转语音或调用google文本转语音TTS。
>
不以英语为母语的人都需要学习英语，市场非常广

**Comment by Pantyhose-X** [comment]
hello @chengluyu 
"listen"keyboard tool,
you can base on [nvda](https://github.com/nvaccess/nvda) 
* Close Screen Reader close all other voice prompts.
* Independent use keyboard Reader![image](https://user-images.githubusercontent.com/42504385/125297889-c4f7f880-e37b-11eb-9731-7e0a20a47545.png)

**Comment by Pantyhose-X** [comment]
> Hi, we’re glad to hear from you! The translation does not very make sense to us. Would you like to rephrase your issue in English?

Always speak typed keys Speak phonetic letters Phonetic letters are spoken when long pressing on keyboard keys and navigating by character.
Applied to language learning. Pronunciation correction
* example，https://www.youtube.com/watch?v=YPBn6D6pf78&feature=youtu.be&t=213
The mother tongue is not English. Need to learn English, the market is very large

"listen"keyboard tool,
you can base on [nvda](https://github.com/nvaccess/nvda) 
* Close Screen Reader close all other voice prompts.
* Independent use keyboard Reader![image](https://user-images.githubusercontent.com/42504385/125297889-c4f7f880-e37b-11eb-9731-7e0a20a47545.png)


[Mozilla's Text-to-Speech](https://github.com/mozilla/TTS)  
[coqui-ai TTS](https://github.com/coqui-ai/TTS) 
[Google Text-to-Speech apk](https://play.google.com/store/apps/details?id=com.google.android.tts&hl=en_US&gl=US)
